import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import type { Plugin } from "@opencode-ai/plugin"

const EDIT_TOOLS = new Set(["write", "edit", "apply_patch"])
const STRUCTURAL_MARKERS = [
  "/android-native/app/src/main/",
  "/ios-native/",
  "/backend/",
  "/data/",
]

function record(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function changedPaths(args: unknown) {
  if (!record(args)) return []
  const direct = [args.filePath, args.filepath, args.path].filter((value): value is string => typeof value === "string")
  const patch = typeof args.patchText === "string" ? args.patchText : ""
  const fromPatch = [...patch.matchAll(/\*\*\* (?:Add|Update|Delete) File: (.+)$/gim)].map((match) => match[1]!.trim())
  return [...new Set([...direct, ...fromPatch])]
}

function structural(worktree: string, filepath: string) {
  const relative = `/${path.relative(worktree, path.resolve(worktree, filepath)).split(path.sep).join("/")}`
  return STRUCTURAL_MARKERS.some((marker) => relative.startsWith(marker))
}

const DocSyncPlugin: Plugin = async (input) => ({
  "tool.execute.after": async (event) => {
    if (!EDIT_TOOLS.has(event.tool)) return
    const paths = changedPaths(event.args)
    if (!paths.some((filepath) => structural(input.worktree, filepath))) return

    const script = path.join(input.worktree, "scripts", "update_kpkn_map.mjs")
    if (await Bun.file(script).exists()) {
      await input.$`node ${script}`.cwd(input.worktree).quiet().nothrow()
    }

    const statusPath = path.join(input.worktree, ".opencode", "doc-sync.md")
    const existing = await readFile(statusPath, "utf8").catch(() => "")
    const affected = paths.map((filepath) => path.relative(input.worktree, path.resolve(input.worktree, filepath)).split(path.sep).join("/"))
    const content = [
      "# KPKN Documentation Sync",
      "",
      "> Generated by KAUPOLIKAN after a structural source edit.",
      `> Last source edit: ${new Date().toISOString()}`,
      "",
      "## Generated Documents",
      "- `.opencode/kpkn-map.md` was refreshed automatically.",
      "",
      "## Curated Documents To Review",
      "- `AGENTS.md`",
      "- `docs/ARCHITECTURE.md`",
      "- `docs/ANDROID_ARCHITECTURE_MAP.md`",
      "- `docs/ANDROID_UI_SCREENS_MAP.md`",
      "",
      "## Affected Source Paths",
      ...affected.map((filepath) => `- ${filepath}`),
      "",
      "Run `/sync-docs` in Auditor mode to propose conservative updates to curated documentation.",
      existing && !existing.includes("Generated by KAUPOLIKAN") ? `\nPrevious status preserved:\n${existing}` : "",
    ]
      .filter(Boolean)
      .join("\n")
    await mkdir(path.dirname(statusPath), { recursive: true })
    await writeFile(statusPath, `${content}\n`, "utf8")
  },
})

export default { id: "doc-sync", server: DocSyncPlugin }
