/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require('nativewind/preset')],
  content: ['./App.tsx', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Material You tokens (dark mode defaults, matching seed #00C8E0) ──
        md: {
          primary: '#5DD5F0',           // Will be overridden at runtime via useTheme
          'on-primary': '#003640',
          'primary-container': '#004E5A',
          'on-primary-container': '#A8EAFF',
          secondary: '#B3CAD4',
          'on-secondary': '#1E333B',
          'secondary-container': '#354A52',
          'on-secondary-container': '#CFE6F0',
          tertiary: '#BCBFE3',
          'on-tertiary': '#272A47',
          'tertiary-container': '#3D415F',
          'on-tertiary-container': '#D9DCFF',
          error: '#FFB4AB',
          'error-container': '#93000A',
          background: '#0E1415',
          'on-background': '#DEE3E4',
          surface: '#0E1415',
          'on-surface': '#DEE3E4',
          'surface-variant': '#3F484B',
          'on-surface-variant': '#BFC8CB',
          'surface-container': '#1A2022',
          'surface-container-high': '#252B2D',
          outline: '#89929A',
          'outline-variant': '#3F484B',
        },
        // ── KPKN semantic tokens ──
        kpkn: {
          'battery-high': '#10C984',
          'battery-mid': '#BCBFE3',
          'battery-low': '#FFB4AB',
          'ring-cns': '#5DD5F0',
          'ring-muscular': '#B3CAD4',
          'ring-spinal': '#BCBFE3',
        },
        // ── Static cyber palette (brand accents, don't change with theme) ──
        cyber: {
          canvas: '#0A0B0E',
          card: '#15171E',
          border: '#2A2D38',
          cyan: '#00F0FF',
          copper: '#FF7B00',
          success: '#00FF9D',
          warning: '#FFD600',
          danger: '#FF2E43',
        },
        // ── Legacy kpkn-* tokens (backward compat with existing components) ──
        'kpkn-bg': '#090B12',
        'kpkn-surface': '#121622',
        'kpkn-elevated': '#1A2030',
        'kpkn-border': 'rgba(255,255,255,0.08)',
        'kpkn-brand': '#00F0FF',
        'kpkn-text': '#F5F7FF',
        'kpkn-muted': '#A7B0C3',
        'kpkn-success': '#32D583',
        'kpkn-warning': '#F5B942',
      },
      fontFamily: {
        sans: ['Inter', 'System'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        // M3 Type Scale (text-display-lg, text-body-md, etc.)
        'display-lg': ['57px', { lineHeight: '64px', fontWeight: '400' }],
        'display-md': ['45px', { lineHeight: '52px', fontWeight: '400' }],
        'display-sm': ['36px', { lineHeight: '44px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'title-sm': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
        card: '24px', // legacy compat
      },
    },
  },
  plugins: [],
};
