package com.example.kpkn.domain.nutrition

import com.example.kpkn.data.db.GlobalFoodEntity
import com.example.kpkn.data.db.toFoodItem
import com.example.kpkn.data.food.FoodImporter
import com.example.kpkn.data.models.FoodItem

/**
 * The committed OFF Chile search fixture (`src/test/resources/food_data/off_chile_search_fixture.tsv`, generated by
 * `scripts/build_off_search_fixture.py`) turned into the rows the importer would store.
 *
 * [entityFromLine] IS `FoodImporter.parseOffLine` (WP-S8): the corpus is exactly what the importer would store, so it
 * can never drift from the importer.
 */
internal object OffSearchFixture {
    private const val RESOURCE = "food_data/off_chile_search_fixture.tsv"

    fun lines(): List<String> {
        val stream = OffSearchFixture::class.java.classLoader!!.getResourceAsStream(RESOURCE)
            ?: error("Missing test resource $RESOURCE")
        return stream.bufferedReader(Charsets.UTF_8).use { reader -> reader.readLines() }
            .map { it.trimEnd('\r') }
            .filter { it.isNotBlank() }
    }

    fun entities(): List<GlobalFoodEntity> = lines().mapNotNull(::entityFromLine)

    fun foods(): List<FoodItem> = entities().map { it.toFoodItem() }

    fun entityFromLine(line: String): GlobalFoodEntity? = FoodImporter.parseOffLine(line)
}
