package com.example.kpkn.domain.nutrition

import com.example.kpkn.data.db.GlobalFoodEntity
import com.example.kpkn.data.db.toFoodItem
import com.example.kpkn.data.food.FoodDescriptionParser
import com.example.kpkn.data.models.FoodItem
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

/**
 * The committed OFF Chile search fixture (`src/test/resources/food_data/off_chile_search_fixture.tsv`, generated by
 * `scripts/build_off_search_fixture.py`) turned into the rows the importer would store.
 *
 * [entityFromLine] mirrors the OFF branch of `FoodImporter.importAll` (same columns, same bounds, same cleaning through
 * [FoodDescriptionParser], same aliases and flags). WP-S8 adds `FoodImporter.parseOffLine`; when it lands this helper
 * should delegate to it so the corpus can never drift from the importer.
 */
internal object OffSearchFixture {
    private const val RESOURCE = "food_data/off_chile_search_fixture.tsv"

    // Column positions of the OFF Chile file (tab separated, no header row).
    private const val CODE = 0
    private const val NAME = 10
    private const val BRAND = 18
    private const val KCAL = 89
    private const val FAT = 92
    private const val CARB = 129
    private const val SUGAR = 130
    private const val FIBER = 146
    private const val PROTEIN = 150
    private const val SODIUM = 156

    fun lines(): List<String> {
        val stream = OffSearchFixture::class.java.classLoader!!.getResourceAsStream(RESOURCE)
            ?: error("Missing test resource $RESOURCE")
        return stream.bufferedReader(Charsets.UTF_8).use { reader -> reader.readLines() }
            .map { it.trimEnd('\r') }
            .filter { it.isNotBlank() }
    }

    fun entities(): List<GlobalFoodEntity> = lines().mapNotNull(::entityFromLine)

    fun foods(): List<FoodItem> = entities().map { it.toFoodItem() }

    fun entityFromLine(line: String): GlobalFoodEntity? {
        val parts = line.split('\t')
        if (parts.size <= SODIUM) return null
        val code = parts[CODE].trim()
        val rawName = parts[NAME].trim()
        if (code.isBlank() || rawName.isBlank()) return null
        val rawBrand = parts[BRAND].trim().takeIf { it.isNotBlank() }

        fun bounded(index: Int, max: Double): Double =
            parts[index].toDoubleOrNull()?.takeIf { it.isFinite() && it in 0.0..max } ?: 0.0
        val kcal = bounded(KCAL, 1000.0)
        val protein = bounded(PROTEIN, 100.0)
        val fat = bounded(FAT, 100.0)
        val carbs = bounded(CARB, 100.0)
        val fiber = bounded(FIBER, 100.0)
        val sugar = bounded(SUGAR, 100.0)
        val sodium = parts[SODIUM].toDoubleOrNull()?.takeIf { it.isFinite() && it in 0.0..5.0 }
        if (parts[SODIUM].isNotBlank() && sodium == null) return null
        val macroEnergy = protein * 4.0 + fat * 9.0 + carbs * 4.0
        if (!(kcal > 0.0 && macroEnergy > 0.0)) return null
        if (kotlin.math.abs(kcal - macroEnergy) / macroEnergy > 0.5) return null

        val parsed = FoodDescriptionParser.parse(
            rawName = rawName,
            rawBrand = rawBrand,
            rawCalories = kcal,
            rawProtein = protein,
            rawFat = fat,
            rawCarbs = carbs,
            rawFiber = fiber,
            rawSugars = sugar,
            rawSodium = sodium ?: 0.0,
            allowDatabaseMatch = false,
        )
        val normalizedName = TextKeys.normalize(parsed.cleanedName)
        val normalizedBrand = parsed.brandHint?.let(TextKeys::normalize)
        val aliases = buildList {
            add(normalizedName)
            if (!normalizedBrand.isNullOrBlank()) add(normalizedBrand)
            parsed.matchedFoodName?.let { add(TextKeys.normalize(it)) }
        }.distinct().filter { it.isNotBlank() }
        // Flags are computed from the RAW values, as FoodImporter.offQualityFlags does.
        val qualityFlags = buildList {
            if (macroEnergy > 0.0 && kotlin.math.abs(kcal - macroEnergy) / macroEnergy > 0.35) add("ENERGY_MISMATCH")
            if (protein <= 0.0 && carbs <= 0.0 && fat <= 0.0) add("INCOMPLETE")
            if (parsed.confidence < 0.6f) add("LOW_QUALITY")
        }
        return GlobalFoodEntity(
            foodId = "off_$code",
            name = parsed.cleanedName,
            brand = parsed.brandHint,
            normalizedName = normalizedName,
            normalizedBrand = normalizedBrand,
            aliasesJson = Json.encodeToString(aliases),
            calories = parsed.calories,
            protein = parsed.protein,
            fats = parsed.fats,
            carbs = parsed.carbs,
            fiber = parsed.fiber,
            sugar = parsed.sugars,
            sodiumMg = parsed.sodiumMg,
            source = "OFF Chile",
            sourcePriority = 80,
            verifiedScore = parsed.confidence.toDouble(),
            sourceRecordId = code,
            foodState = "UNKNOWN",
            nutritionBasis = "PER_100G_AS_SOLD",
            datasetVersion = "9",
            qualityFlagsJson = if (qualityFlags.isEmpty()) "[]" else qualityFlags.joinToString(",", "[", "]") { "\"$it\"" },
        )
    }
}
