package com.example.kpkn.domain.relator

import com.example.kpkn.data.models.AutoregulationMode
import com.example.kpkn.data.models.BlockGoal
import com.example.kpkn.data.protocols.LoadBasis
import com.example.kpkn.data.protocols.ProgressionRule
import com.example.kpkn.data.protocols.SlotRole
import com.example.kpkn.data.protocols.TechniqueModifier

internal fun relatorContext(
    sessionId: String = "s1",
    setKey: String = "ex_0",
    idleCycle: Int = 1,
    phase: RelatorSessionPhase = RelatorSessionPhase.WORKING,
    exerciseName: String = "Sentadilla",
    exerciseId: String = "ex",
    setIndex: Int = 0,
    setCount: Int = 5,
    slotRole: SlotRole? = SlotRole.T1_MAIN,
    isTopSet: Boolean = false,
    isAmrap: Boolean = false,
    targetPercentageRm: Double? = 75.0,
    prescribedWeightKg: Double? = 92.5,
    suggestedWeightKg: Double? = 92.5,
    protocolId: String? = "wendler-531-bbb",
    protocolName: String? = "5/3/1 BBB",
    weekIndex: Int? = 3,
    weeksInBlock: Int? = 4,
    blockGoal: BlockGoal? = BlockGoal.INTENSIFICATION,
    progression: ProgressionRule? = ProgressionRule.AmrapDrivenTm(),
    autoregulationMode: AutoregulationMode = AutoregulationMode.PROPOSE,
    dailyScore: Int? = 72,
    lastSets: List<RelatorHistorySet> = listOf(
        RelatorHistorySet(90.0, 5),
        RelatorHistorySet(90.0, 5),
        RelatorHistorySet(92.5, 4),
    ),
    bestRm: Double = 140.0,
    completed: Int = 4,
    total: Int = 20,
    restActive: Boolean = false,
    prJustNow: Boolean = false,
    warmupRemaining: Int = 0,
    conceptId: String? = null,
    conceptLines: List<String> = emptyList(),
    executionCues: List<String> = emptyList(),
    coachBody: String? = null,
    mediaCount: Int = 0,
    feminine: Boolean = false,
    userReacted: Boolean = false,
    visible: Boolean = true,
    techniqueModifier: TechniqueModifier? = null,
    loadBasis: LoadBasis? = LoadBasis.PERCENT_TM,
    minutesAhead: Int? = 4,
    isCompetitionLift: Boolean = false,
): RelatorContext = RelatorContext(
    sessionId = sessionId,
    setKey = setKey,
    idleCycle = idleCycle,
    feminine = feminine,
    visible = visible,
    phase = phase,
    exerciseId = exerciseId,
    exerciseName = exerciseName,
    setIndex = setIndex,
    setCount = setCount,
    slotRole = slotRole,
    isTopSet = isTopSet,
    loadBasis = loadBasis,
    techniqueModifier = techniqueModifier,
    isAmrap = isAmrap,
    isCompetitionLift = isCompetitionLift,
    targetPercentageRm = targetPercentageRm,
    prescribedWeightKg = prescribedWeightKg,
    suggestedWeightKg = suggestedWeightKg,
    targetReps = 5,
    executionCues = executionCues,
    userReacted = userReacted,
    conceptId = conceptId,
    conceptLines = conceptLines,
    plan = RelatorPlanSlice(
        sourceProtocolId = protocolId,
        sourceProtocolName = protocolName,
        autoregulationMode = autoregulationMode,
        blockGoal = blockGoal,
        weekIndexInBlock = weekIndex,
        weeksInBlock = weeksInBlock,
        progression = progression,
    ),
    history = RelatorHistorySlice(
        lastSessionSets = lastSets,
        trendThreeSessionsKg = lastSets.map { it.weightKg },
        bestEstimatedRmKg = bestRm,
        distanceToBestKg = 2.5,
    ),
    progress = RelatorProgressSlice(
        completedWorkingSets = completed,
        totalWorkingSets = total,
        elapsedMinutes = 18,
        targetDurationMinutes = 60,
        remainingSeconds = 2_400,
        minutesAhead = minutesAhead,
        nextExerciseName = "Press banca",
        nextSuggestedKg = 80.0,
    ),
    rest = RelatorRestSlice(
        active = restActive,
        remainingSeconds = if (restActive) 90 else 0,
        plannedSeconds = 180,
        adaptiveSeconds = 210,
        justHitPr = prJustNow,
        overlayMinimized = true,
    ),
    readiness = RelatorReadinessSlice(
        dailyScore = dailyScore,
        dailyLabel = "Moderada",
        exerciseScore = dailyScore,
        sleepQuality = 3,
        stressLevel = 3,
        doms = 2,
    ),
    warmup = RelatorWarmupSlice(
        remainingCount = warmupRemaining,
        suggestedKg = 60.0,
        count = 3,
        isLastIncomplete = warmupRemaining == 1,
    ),
    coach = RelatorCoachSlice(key = coachBody?.let { "k" }, title = coachBody, body = coachBody),
    media = RelatorMediaSlice(previousCount = mediaCount, previousExerciseName = exerciseName),
    milestone = RelatorMilestoneSlice(prJustNow = prJustNow, estimatedRmKg = if (prJustNow) 142.0 else null),
)
