import type { NutritionKnownFoodHint } from '@kpkn/shared-types';

export const LOCAL_CHILEAN_FOOD_CATALOG: NutritionKnownFoodHint[] = [
  {
    id: 'cl001',
    name: 'Pan con Palta y Jamón',
    servingSize: 160,
    unit: 'g',
    calories: 365,
    protein: 14,
    carbs: 31,
    fats: 20,
    tags: ['desayuno', 'preparacion', 'chileno'],
  },
  {
    id: 'cl002',
    name: 'Batido de Proteína con Plátano y Leche',
    servingSize: 450,
    unit: 'ml',
    calories: 340,
    protein: 31,
    carbs: 34,
    fats: 8,
    tags: ['batido', 'preparacion'],
  },
  {
    id: 'cl003',
    name: 'Porotos con Riendas',
    servingSize: 350,
    unit: 'g',
    calories: 405,
    protein: 18,
    carbs: 57,
    fats: 10,
    tags: ['legumbre', 'preparacion', 'chileno'],
  },
  {
    id: 'cl004',
    name: 'Humita',
    servingSize: 220,
    unit: 'g',
    calories: 255,
    protein: 6,
    carbs: 42,
    fats: 7,
    tags: ['preparacion', 'chileno'],
  },
  {
    id: 'cl005',
    name: 'Pebre',
    servingSize: 50,
    unit: 'g',
    calories: 32,
    protein: 1,
    carbs: 5,
    fats: 1,
    tags: ['acompanamiento', 'chileno'],
  },
  {
    id: 'cl006',
    name: 'Sopaipilla',
    servingSize: 90,
    unit: 'g',
    calories: 230,
    protein: 4,
    carbs: 31,
    fats: 10,
    tags: ['snack', 'chileno'],
  },
];
