from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[4]
PRIVATE=Path(__file__).resolve().parent
sys.path.insert(0,str(ROOT/'scripts'))
import catalog_v2_sources as registry
BASE=ROOT/'artifacts/catalog-lote07-preparation-20261005/rebase_actual'
PROOF=json.loads((BASE/'baseline_inputs/sources_verified.json').read_text(encoding='utf-8'))['sources']
LOCAL=json.loads((PRIVATE/'sources_verified.json').read_text(encoding='utf-8'))['sources']
for url,entry in LOCAL.items(): PROOF.setdefault(url,entry)
missing=[p for p in ['35586943','33780488','36096478','30946266'] if f'https://pubmed.ncbi.nlm.nih.gov/{p}/' not in PROOF]
NEW=registry.pubmed_summary(missing) if missing else {}
def source(id,pmid,claim):
    url=f'https://pubmed.ncbi.nlm.nih.gov/{pmid}/'
    title=PROOF[url]['title'] if url in PROOF else NEW[pmid]['title']
    return dict(id=id,url=url,title=title,claim=claim)
def page(id,url,title,claim): return dict(id=id,url=url,title=title,claim=claim)
def muscle(id,role,why,*sources): return dict(id=id,role=role,why=why,sources=list(sources))
def joint(id,role,actions,why,*sources): return dict(id=id,role=role,actions=actions,why=why,sources=list(sources))
def cfg(desc,setup,execution): return dict(description=desc,setupCues=setup,executionCues=execution)
def phase(name,description): return dict(name=name,description=description)
GM=source('gm_anatomy','30855781','La extensión de cadera es una función del glúteo mayor; esa función fundamenta el motor de la elevación pélvica, sin inferir un porcentaje de activación.')
HAM=source('ham_anatomy','31536294','Los isquiosurales que cruzan la cadera asisten su extensión y flexionan la rodilla; la flexión de rodilla modifica su longitud en el puente.')
CORE=source('abdominal_wall','31869113','La pared abdominal participa en el control de la columna y la presión intraabdominal; su estabilización se interpreta según el montaje descrito.')
MED=source('gmmed_anatomy','32491441','El glúteo medio interviene en la estabilidad de pelvis y miembro inferior; el sostén unilateral no equivale a una abducción dinámica resistida.')
PELVIC=source('pelvic_joints','30860758','La articulación sacroilíaca transmite fuerzas entre pelvis y miembros inferiores con movilidad pequeña, sin convertirse en motor de la repetición.')
HIP=source('hip_joint','29262200','La cadera permite flexión, extensión, abducción y rotación; distingue el movimiento extensor de una postura abductada y externamente rotada.')
FOREARM=source('forearm_anatomy','30969606','Los flexores de dedos y muñeca intervienen en el agarre; la función estabilizadora depende de sujetar una carga o las asas que fijan el cuerpo.')
BRIDGE=source('bridge_emg','25671354','En puentes supinos estables y unilaterales se registró actividad glútea, isquiosural y de multífidos; las mayores señales por músculo correspondieron a condiciones diferentes.')
KENNEDY=source('bridge_thrust_emg','35586943','Comparó puente con barra e hip thrust con barra: ambos reclutan extensores de cadera y el hip thrust mostró mayor señal del vasto lateral en esa muestra; la EMG no prueba hipertrofia.')
BRAZIL=source('thrust_kinetics','33780488','En hip thrust bilateral con barra la demanda extensora de cadera superó a rodilla y pelvis-tronco; el momento de cadera disminuyó durante la subida en lugar de permanecer constante.')
EVOLUTION=page('bridge_demonstrations','https://bretcontreras.com/the-evolution-of-the-hip-thrust/','The Evolution of the Hip Thrust','Demostraciones de puente en suelo, con barra y a una pierna, además de puente unilateral en Smith; distingue el apoyo en suelo del apoyo elevado del hip thrust.')
NASM=page('floor_bridge_demo','https://www.nasm.org/resource-center/blog/training/why-the-glute-bridge-belongs-in-almost-every-client-program','Why the Glute Bridge Belongs in Almost Every Client Program','Describe el puente supino en suelo y sus progresiones con mancuerna y a una pierna; respalda los apoyos y la carga pélvica, sin comparar resultados de entrenamiento.')
UNILATERAL=page('thrust_variations','https://bretcontreras.com/single-leg-hip-thrusts/','How to Perform Single-Leg Hip Thrusts (12 Excellent Variations)','Incluye montajes unilaterales en Smith y con banda anclada al rack, con espalda alta elevada y una pierna libre; no se trasladan sus opiniones sobre curvas a la barra.')
PANATTA=page('thrust_machine','https://panattaturkiye.com/fit-evo---hip-thrust','Fit Evo - Hip Thrust','La página del modelo Panatta 1FE097 publica fotos y demostración del fabricante, plataforma de pies y rodillo de empuje ajustable; respalda la estación real elegida.')
FROG=page('frog_demo','https://bretcontreras.com/frog-pumps-a-highly-effective-bodyweight-glute-activation-drill/','Frog Pumps: A Highly Effective Bodyweight Glute Activation Drill','Demuestra un puente en suelo con plantas juntas, rodillas abiertas y codos apoyados. Es una referencia de técnica, no evidencia experimental de aislamiento muscular.')
RHE19=source('rhe_biomechanics','30946266','En Reverse Hyper se midieron momento lumbar, actividad de erectores y movimiento entre pelvis y tronco; el apoyo superior no inmovilizó la región lumbar.')
RHE22=source('rhe_load','36096478','Registró actividad del glúteo mayor, bíceps femoral y erectores junto a movimiento del tronco y las piernas; cargas mayores alteraron la flexión del tronco y la cadera.')
ROGUE=page('rhe_machine','https://www.roguefitness.com/gb/westside-scout-hyper-eu','Westside Scout Hyper','La estación real tiene plataforma acolchada, asas, péndulo con postes de carga y correa para los pies; no es una extensión del tronco sobre apoyo a cuarenta y cinco grados.')

bridge_configs={
 'glutes_puente_gluteos__bilateral__barbell':cfg('La barra acolchada cruza la pelvis y ambos pies empujan desde el suelo. El apoyo de los hombros queda a ras de la colchoneta, de modo que la subida termina al alinear caderas y muslos.', ['Túmbate boca arriba y deja ambos pies planos, separados a la anchura de la cadera.','Centra el eje sobre el acolchado pélvico y sostén la barra por fuera de las caderas.'],['Eleva la pelvis hasta alinear hombros, caderas y rodillas.','Baja la pelvis a la colchoneta sin perder el contacto de los pies.']),
 'glutes_puente_gluteos__unilateral__barbell':cfg('Un pie queda suspendido y la pierna de apoyo eleva la pelvis bajo una barra transversal. Las manos impiden que la carga ruede o se incline cuando la base de apoyo pasa a un solo lado.', ['Sitúa la barra sobre la pelvis con acolchado y agarra el eje a ambos lados.','Deja un pie plano y eleva la otra pierna con la rodilla doblada.'],['Levanta ambas caderas a la misma altura con la pierna apoyada.','Baja con la pierna elevada sin hacer contacto de ese pie ni inclinar el eje.']),
 'glutes_puente_gluteos__bilateral__dumbbells':cfg('Una mancuerna horizontal añade peso sobre la parte anterior de las caderas, sujeta por las dos manos. Con los dos pies plantados y la espalda alta en el suelo, resulta un montaje compacto para sumar carga al puente.', ['Apoya una mancuerna horizontal sobre la pelvis y sostén sus extremos.','Dobla las rodillas y planta los dos pies cerca de los glúteos.'],['Empuja el suelo con ambos pies para levantar la pelvis.','Regresa al apoyo inferior sin deslizar la mancuerna hacia el abdomen.']),
 'glutes_puente_gluteos__unilateral__dumbbells':cfg('La carga corta puede descansar sobre la cadera de la pierna que empuja, sin un eje largo que sobresalga a los lados. La pierna sin apoyo permanece flexionada, mientras el glúteo medio ayuda al sostén de esa mitad de la pelvis.', ['Sujeta una mancuerna sobre el pliegue de la cadera de apoyo.','Recoge la pierna libre y deja el otro pie firme sobre la colchoneta.'],['Sube la pelvis sin girarla hacia la pierna suspendida.','Baja hasta rozar el suelo mientras sostienes la mancuerna sobre la cadera.']),
 'glutes_puente_gluteos__bilateral__smith_machine':cfg('Los carriles encauzan la barra acolchada sobre la pelvis mientras las dos piernas empujan a la vez. El cuerpo permanece tendido en el suelo y la altura de los topes debe permitir el descenso pélvico de esta posición.', ['Ajusta los topes de la Smith para permitir el recorrido desde el suelo.','Túmbate bajo la barra acolchada con las caderas centradas y ambos pies plantados.'],['Desengancha la barra y eleva la pelvis sin levantar los hombros.','Desciende hasta la colchoneta y vuelve a enganchar al acabar.']),
 'glutes_puente_gluteos__unilateral__smith_machine':cfg('La Smith limita el desplazamiento lateral del eje, pero un único pie produce el empuje. El lado sin apoyo permanece suspendido durante toda la repetición; la guía de la barra no sustituye el sostén de la pelvis.', ['Centra las caderas bajo la barra guiada y sujétala antes de desenganchar.','Acerca el pie de apoyo y eleva la rodilla de la pierna libre.'],['Extiende la cadera apoyada sin dejar caer el otro lado de la pelvis.','Baja despacio con el pie libre en el aire.']),
 'glutes_puente_gluteos__bilateral__bodyweight':cfg('Sin peso añadido, los dos pies y la espalda alta forman la base que permite levantar la pelvis. El glúteo mayor aporta la extensión de cadera, con un recorrido delimitado por el contacto inicial del cuerpo con el suelo.', ['Túmbate sobre una colchoneta con las rodillas dobladas y los pies planos.','Deja los brazos junto al cuerpo y los hombros apoyados.'],['Eleva las caderas hasta formar una línea entre hombros y rodillas.','Vuelve a apoyar la pelvis sin arquear la zona lumbar.'])
}
bridge={
 'status':'CURATED',
 'public':{'description':'El Puente de Glúteos desarrolla la extensión de cadera con el glúteo mayor como motor y los isquiosurales como ayuda. La espalda alta descansa en el suelo mientras la pelvis se eleva entre los hombros y los pies, con un recorrido más corto que el apoyo elevado. El abdomen estabiliza el tronco para que la subida nazca en las caderas. Una pierna libre añade demanda de sostén pélvico. Es una forma de cargar la extensión de cadera desde una posición baja y con apoyos definidos.','configurations':bridge_configs},
 'anatomy':{'muscles':[
  muscle('gluteus_maximus','PRIMARY','Eleva la pelvis al extender la cadera entre los pies y los hombros apoyados; se conserva como dominante también en el puente corporal protegido.','gm_anatomy','bridge_emg','bridge_thrust_emg'),
  muscle('hamstrings','SECONDARY','Las porciones biarticulares ayudan a levantar la pelvis desde la cadera; la rodilla doblada limita su longitud y el gesto no es un curl de rodilla.','ham_anatomy','bridge_emg'),
  muscle('core','STABILIZER','La pared abdominal enlaza el tórax apoyado con la pelvis elevada y frena la extensión lumbar que sustituiría parte del movimiento de cadera.','abdominal_wall','floor_bridge_demo'),
  muscle('forearm','STABILIZER','El agarre de las manos frena el deslizamiento del peso sobre la pelvis; no levanta esa carga desde el suelo como un tirón con los brazos.','forearm_anatomy','bridge_demonstrations')],
 'joints':[
  joint('cadera','PRIMARY',['Extensión de cadera'],'La pelvis asciende respecto de los muslos con apoyo superior en el suelo; la extensión coxofemoral produce la elevación del cuerpo y del peso añadido.','hip_joint','bridge_emg'),
  joint('rodilla','STABILIZER',['Sostén en flexión'],'El pie fijo y la rodilla doblada constituyen el apoyo inferior; no se programa flexión o extensión de rodilla para elevar la pelvis en este puente.','floor_bridge_demo','ham_anatomy'),
  joint('columna-lumbar','STABILIZER',['Control de la extensión lumbar'],'La zona lumbar deja la colchoneta al subir, pero su arco no debe crecer para ganar altura; el control abdominal conserva la relación entre tórax y pelvis.','abdominal_wall','floor_bridge_demo'),
  joint('sacroiliaca','STABILIZER',['Transferencia de fuerza pélvica'],'Transmite al sacro la fuerza que llega a cada hemipelvis desde los pies, sin una apertura sacroilíaca que forme parte visible de la repetición.','pelvic_joints')],
 'overrides':{}},
 'technique':{'identity':'Extensión de cadera supina con la espalda alta y los hombros en el suelo, pelvis inicialmente baja y pies plantados. La pelvis sube hacia la línea entre hombros y rodillas; el apoyo superior a ras del suelo delimita su identidad.','setup':['Colchoneta estable bajo el cuerpo, rodillas dobladas y pies planos a una distancia que permita tibias próximas a vertical al final.','Con ambas plantas apoyadas, la separación corresponde a la anchura pélvica; con un solo pie activo, la otra pierna está flexionada en el aire.','La barra libre o guiada cruza la pelvis con acolchado; una mancuerna descansa sobre las caderas y se sujeta con las manos. La configuración corporal no añade peso.'],'keyPositions':['Inicio: espalda alta y pelvis sobre la colchoneta, rodillas flexionadas y carga sobre los pliegues de las caderas cuando corresponda.','Arriba: hombros en el suelo, pelvis elevada, muslo y tronco alineados, rodilla de apoyo doblada y tibia próxima a vertical.'],'mistakes':['Elevar los hombros a un banco o colocar los pies en una plataforma distinta del suelo.','Subir arqueando la región lumbar mientras la cadera permanece flexionada.','Dejar que el lado libre de la pelvis caiga durante el apoyo unilateral.','Permitir que la carga ruede desde los pliegues de las caderas hacia el abdomen.'],'phases':[phase('Elevación','Los pies empujan la superficie y las caderas se extienden; el peso pélvico acompaña al cuerpo sin ser izado por los brazos.'),phase('Alineación superior','La pelvis alcanza la línea del tronco y los muslos, con los hombros aún en la colchoneta y sin aumentar el arco lumbar.'),phase('Retorno al suelo','Las caderas flexionan para devolver la pelvis al apoyo inferior; las manos sujetan la carga durante el descenso cuando existe.')]},
 'visual':{'base':{'camera':'Vista lateral ligeramente oblicua que muestra el suelo, ambos lados de la pelvis y los pies.','phase':'Pelvis en el punto superior de la extensión, con hombros todavía sobre el suelo.','orientation':'Cuerpo boca arriba, cabeza a la izquierda del encuadre y pies a la derecha.','contacts':'Espalda alta y hombros apoyados en el suelo; uno o dos pies plantados según lateralidad, pelvis separada del suelo.','posture':'Rodillas flexionadas y caderas alineadas con los muslos, sin arco lumbar exagerado.','load':'El peso corporal asciende con la pelvis y cualquier resistencia adicional descansa sobre las caderas.'},
 'byImplement':{'barbell':{'geometry':'Barra transversal acolchada sobre los pliegues de las caderas, discos simétricos fuera del cuerpo; ambas manos agarran el eje y los discos quedan elevados respecto del suelo en el fotograma superior.'},'dumbbells':{'geometry':'Una mancuerna corta horizontal sobre la pelvis en el apoyo bilateral; en unilateral descansa sobre el pliegue de la cadera de apoyo. Ambas manos impiden su rodamiento y la pelvis está elevada sobre la colchoneta.'},'smith_machine':{'geometry':'Estación Smith completa con carriles verticales, barra acolchada transversal sobre la pelvis y discos en ambos extremos. Hombros directamente sobre la colchoneta bajo el eje; manos agarrando la barra y topes por debajo del recorrido usado.'},'bodyweight':{'geometry':'Atleta sobre una colchoneta sin peso externo, ambos pies planos separados a anchura de cadera, brazos junto al cuerpo y hombros en el suelo mientras la pelvis está elevada.'}},
 'promptCore':{'barbell':'Three-quarter side view, frozen at the TOP of a floor barbell glute bridge. Upper back and shoulders rest directly on a floor mat; both feet are flat on the floor, knees bent. A padded barbell lies across the hip creases. Both hands grip the shaft beside the pelvis to stop it rolling. Hips align with shoulders and knees, ribs low. Both loaded bar ends are clear of the floor. No text or logos.','dumbbells':'Oblique side view, frozen at the TOP of a floor dumbbell glute bridge. Shoulders and upper back are on a floor mat, both feet flat and knees bent. One short dumbbell rests horizontally on the front of the raised pelvis, held in place by both hands. Torso and thighs form a straight line, with no exaggerated lower-back arch. The dumbbell and pelvis are clear of the floor. No text or logos.','smith_machine':'Side view, frozen at the TOP of a floor glute bridge inside a full vertical Smith station. Shoulders and upper back rest directly on a floor mat, both feet flat and knees bent. The padded guided bar rests across the raised hip creases; both hands grip the bar. Hips align with shoulders and knees. Plates at both ends are above the floor; the bar stays attached to the rails. No text or logos.','bodyweight':'Oblique side view, frozen at the TOP of a bodyweight floor glute bridge. Shoulders and upper back press into a floor mat; both bare palms rest beside the body. Both feet are flat and knees bent. The pelvis is raised until hips, knees and shoulders form one line, without excessive back arch. No weight rests on the pelvis; no bench, text or logos.'},
 'forbidden':['Hombros sobre un banco elevado: ese apoyo cambia el ejercicio a hip thrust.','Pelvis abajo con el cuerpo completamente tendido en vez del fotograma superior.','Barra o mancuerna flotando por encima del cuerpo, sin contacto pélvico ni manos que la sujeten.','Dos pies en el suelo en una configuración unilateral, o pie libre apoyado sobre el otro.','Rodillas que se abren repetidamente contra una banda: añade una acción resistida de abducción con glúteo medio principal que este montaje no incluye.'],
 'qa':['¿La espalda alta y los hombros están directamente sobre el suelo?','¿La pelvis está elevada y alineada con el muslo de apoyo en el fotograma superior?','¿La carga añadida toca la pelvis y las manos la sujetan, o el montaje corporal carece de peso externo?','¿Hay un solo pie plantado en unilateral y dos en bilateral?','¿Las rodillas no realizan una apertura contra resistencia externa?'],
 'byVariant':{}},
 'sources':[GM,HAM,CORE,MED,PELVIC,HIP,FOREARM,BRIDGE,KENNEDY,EVOLUTION,NASM]}
for cid in bridge_configs:
 if '__unilateral__' in cid:
  bridge['anatomy']['overrides'][cid]={'muscles':[muscle('gluteus_medius','STABILIZER','La única pierna apoyada deja una demanda de sostén frontal de la pelvis; el glúteo medio limita su caída sin una apertura lateral contra carga.','bridge_emg','gmmed_anatomy')],'joints':[joint('cadera','PRIMARY',['Extensión de cadera'],'La cadera de una sola pierna eleva el cuerpo y la carga pélvica; la pierna recogida queda fuera del apoyo y exige sostén de la pelvis en el plano frontal.','hip_joint','bridge_emg'),joint('sacroiliaca','STABILIZER',['Transferencia asimétrica de fuerza'],'La fuerza entra principalmente por la hemipelvis del pie de apoyo; el anillo pélvico la transmite al tronco sin una rotación deliberada entre sacro e ilion.','pelvic_joints')]}
  bridge['visual']['byVariant'][cid]={'difference':'Un único pie está plano en el suelo; la otra pierna queda recogida y suspendida. Las dos caderas alcanzan una altura similar, sin que la libre caiga; la carga está sujeta sobre la pelvis.'}
bridge['anatomy']['overrides']['glutes_puente_gluteos__bilateral__bodyweight']={'muscles':[{'id':'forearm','role':'NONE','why':'Los brazos reposan sobre la colchoneta y no sujetan una carga ni sostienen el cuerpo mediante un agarre.'}],'joints':[joint('cadera','PRIMARY',['Extensión de cadera'],'Los dos pies elevan la pelvis frente al peso del propio cuerpo; no hay resistencia añadida sobre los pliegues de las caderas, con igual movimiento extensor.','hip_joint','floor_bridge_demo')]}
bridge['anatomy']['overrides']['glutes_puente_gluteos__bilateral__smith_machine']={'joints':[joint('cadera','PRIMARY',['Extensión de cadera'],'La pelvis eleva la barra a lo largo de los carriles desde el suelo; la guía restringe su desplazamiento y la cadera continúa produciendo la elevación.','hip_joint','bridge_demonstrations')]}

thrust_configs={
 'hip_thrust__bilateral__barbell':cfg('El eje acolchado descansa sobre las caderas y ambas piernas lo elevan con la espalda alta sobre un banco. Los discos permiten graduar el peso, mientras las manos sujetan la barra para que no ruede sobre el cuerpo.', ['Fija un banco detrás de la espalda alta y planta ambos pies.','Apoya la barra acolchada sobre las caderas y agarra el eje por fuera del cuerpo.'],['Eleva la pelvis hasta extender las caderas con las tibias casi verticales.','Baja desde la cadera mientras los hombros siguen en contacto con el banco.']),
 'hip_thrust__unilateral__barbell':cfg('Una sola pierna levanta la pelvis y una barra libre, con la otra rodilla recogida en el aire. La longitud del eje exige sujeción manual a ambos lados y la pelvis recibe apoyo inferior únicamente del pie que empuja.', ['Centra la barra sobre la pelvis con acolchado y sujétala a ambos lados.','Apoya la espalda alta en el banco y recoge una pierna sin tocar el suelo.'],['Extiende la cadera de apoyo sin inclinar la barra.','Desciende con el pie libre suspendido y los hombros sobre el banco.']),
 'hip_thrust__bilateral__smith_machine':cfg('La barra de la Smith recorre sus carriles mientras los dos pies empujan desde el suelo. La ubicación del banco respecto del eje determina dónde queda la pelvis; la guía reduce el desplazamiento lateral de la carga.', ['Alinea la pelvis bajo la barra de la Smith con la espalda alta sobre el banco.','Prepara los topes y sujeta la barra acolchada antes de desenganchar.'],['Sube con ambos pies firmes sin deslizar los hombros del banco.','Baja hasta flexionar las caderas dentro del recorrido disponible.']),
 'hip_thrust__unilateral__smith_machine':cfg('El carril sujeta el eje lateralmente y un único pie aporta el empuje de abajo. La pierna suspendida deja al glúteo medio una tarea de sostén pélvico, aunque el eje ya quede sujeto por los carriles.', ['Sitúa un pie bajo su rodilla y eleva la pierna libre.','Sujeta la barra acolchada sobre las caderas con la espalda alta apoyada en el banco.'],['Levanta la pelvis sin girar hacia el lado libre.','Vuelve al punto bajo sin que el pie suspendido ayude.']),
 'hip_thrust__bilateral__machine':cfg('El rodillo de empuje comprime la parte anterior de la pelvis y el respaldo basculante acompaña al tronco. Los dos pies cargan la plataforma de la estación, con una entrada y un ajuste propios de ese mecanismo.', ['Ajusta el respaldo y el rodillo a tu pelvis siguiendo la estación.','Coloca ambos pies planos sobre la plataforma y agarra las asas.'],['Empuja la plataforma hasta extender las caderas bajo el rodillo.','Devuelve el rodillo al inicio mientras la espalda sigue apoyada.']),
 'hip_thrust__unilateral__machine':cfg('Sobre la misma plataforma queda un pie activo y el otro sale del apoyo. El rodillo conserva el contacto sobre ambas caderas, pero la fuerza que lo eleva procede de un lado; la espalda acompaña la inclinación del respaldo móvil.', ['Ajusta el rodillo y el respaldo antes de liberar un pie de la plataforma.','Recoge la pierna libre y agarra las asas con ambas manos.'],['Eleva el rodillo desde la cadera de apoyo sin torcer la pelvis.','Regresa con el pie libre fuera de la plataforma.']),
 'hip_thrust__bilateral__band':cfg('Una banda larga cruza las caderas y se fija a dos anclajes bajos a los lados del banco. Su estiramiento aumenta al subir la pelvis con ambos pies, añadiendo resistencia a la extensión sin cargar las rodillas hacia dentro.', ['Fija una banda larga a dos anclajes bajos del rack y pásala sobre las caderas.','Apoya la espalda alta en un banco estable y los dos pies en el suelo.'],['Eleva la pelvis contra la banda sin deslizar su contacto hacia el abdomen.','Baja con ambos pies planos y los hombros sobre el banco.']),
 'hip_thrust__unilateral__band':cfg('El elástico anclado a los lados tira de la pelvis hacia abajo y solo un pie responde a esa resistencia. La pierna opuesta está flexionada; el aumento de estiramiento arriba se suma a la exigencia de sostener la pelvis sin caída lateral.', ['Pasa la banda anclada a los lados sobre la pelvis, sin rodear las rodillas.','Con la espalda alta apoyada, recoge una pierna y planta el pie activo.'],['Sube desde la cadera apoyada hasta estirar la banda sin girar el tronco.','Desciende sin que el pie libre contacte con el suelo.'])}
thrust={
 'status':'CURATED','public':{'description':'El Hip Thrust carga la extensión de cadera y da protagonismo al glúteo mayor, con ayuda de isquiosurales y cuádriceps. Un apoyo elevado sostiene la espalda alta y permite que la pelvis baje antes de subir entre el torso y los muslos. El abdomen sostiene la relación entre costillas y pelvis durante ese recorrido. La variante a una pierna añade trabajo de sostén lateral. Su rasgo propio es elevar una pelvis cargada entre el apoyo alto de los hombros y los pies plantados delante del cuerpo.','configurations':thrust_configs},
 'anatomy':{'muscles':[
  muscle('gluteus_maximus','PRIMARY','Es el motor que extiende la cadera y eleva la pelvis bajo la carga con apoyo torácico elevado; la demanda extensora de cadera supera la de rodilla.','gm_anatomy','thrust_kinetics'),
  muscle('hamstrings','SECONDARY','Sus cabezas que cruzan la cadera ayudan al empuje pélvico; las rodillas flexionadas reducen su longitud y no convierten la tarea en extensión de rodilla.','ham_anatomy','bridge_thrust_emg'),
  muscle('quadriceps','SECONDARY','Aporta demanda extensora en la rodilla mientras el pie fija el apoyo inferior; el vasto lateral se activa en el hip thrust estudiado y no domina sobre la cadera.','thrust_kinetics','bridge_thrust_emg'),
  muscle('core','STABILIZER','Sostiene el enlace de costillas y pelvis cuando el torso gira sobre su apoyo; limita que la elevación pélvica se complete a costa de arquear la zona lumbar.','abdominal_wall','thrust_kinetics'),
  muscle('forearm','STABILIZER','Las manos sujetan el eje, las asas o la banda según la estación; ese agarre fija el contacto y evita desplazamientos ajenos a la extensión de cadera.','forearm_anatomy','thrust_variations','thrust_machine')],
 'joints':[
  joint('cadera','PRIMARY',['Extensión de cadera'],'La carga se eleva desde una pelvis baja entre el apoyo torácico y los pies; la cadera realiza el mayor cambio extensor útil durante el empuje.','hip_joint','thrust_kinetics'),
  joint('rodilla','SECONDARY',['Extensión de rodilla durante el empuje'],'El pie plantado transmite fuerza y el ángulo de rodilla cambia con el arco del cuerpo; la demanda extensora medida es menor que la de cadera, pero no nula.','thrust_kinetics','bridge_thrust_emg'),
  joint('columna-lumbar','STABILIZER',['Sostén lumbopélvico'],'El apoyo elevado sostiene el tórax mientras la pelvis se mueve; la relación lumbar se vigila para que el recorrido de cadera no se reemplace con hiperextensión.','abdominal_wall','thrust_kinetics'),
  joint('sacroiliaca','STABILIZER',['Transmisión de fuerzas entre pelvis y tronco'],'El empuje de los pies llega al sacro a través de la pelvis y se transmite al torso apoyado; no se busca una movilidad sacroilíaca adicional para levantar la carga.','pelvic_joints')], 'overrides':{}},
 'technique':{'identity':'Empuje pélvico supino con el apoyo superior elevado bajo la espalda alta y los pies delante del cuerpo. La pelvis baja entre ellos y asciende al extender las caderas; el torso pivota sobre su apoyo o acompaña el respaldo móvil de la estación.','setup':['Banco estable bajo la zona inferior de las escápulas para las configuraciones libres, guiadas o elásticas; en máquina se usa el respaldo basculante propio.','Pies planos delante del cuerpo, con tibias aproximadamente verticales en la posición alta; una sola planta participa en unilateral.','Barra acolchada sobre los pliegues de las caderas, banda larga sobre la pelvis con anclajes bajos laterales, o rodillo pélvico de máquina con su plataforma y asas.'],'keyPositions':['Abajo: pelvis más baja que la espalda alta y caderas flexionadas, con hombros aún apoyados y pies firmes.','Arriba: pelvis elevada hasta alinear el torso con el muslo de apoyo, rodilla doblada y resistencia en contacto con la parte anterior de las caderas.','Unilateral: rodilla libre recogida y pie suspendido, sin segundo contacto inferior ni descenso del lado libre de la pelvis.'],'mistakes':['Convertir la variante unilateral en un apoyo escalonado con dos pies plantados.','Desplazar el contacto superior hacia el cuello en lugar de la espalda alta.','Levantar las costillas y arquear la zona lumbar para simular mayor altura de pelvis.','Colocar la banda únicamente alrededor de las rodillas en vez de sobre la pelvis anclada.'],'phases':[phase('Empuje','El apoyo inferior produce la elevación de la pelvis contra la resistencia situada sobre las caderas, con la espalda alta en su superficie de sostén.'),phase('Extensión alcanzada','El torso y el muslo de apoyo se alinean, con el contacto pélvico de la carga intacto y sin proyectar las costillas hacia arriba.'),phase('Descenso pélvico','Las caderas flexionan y la pelvis vuelve por debajo del apoyo superior; el torso gira junto al respaldo o sobre el borde del banco.')]},
 'visual':{'base':{'camera':'Vista lateral oblicua con apoyo superior, pelvis, resistencia y pies visibles en el mismo encuadre.','phase':'Extensión superior de cadera, con pelvis elevada y resistencia en contacto sobre ella.','orientation':'Atleta boca arriba sobre un apoyo superior elevado, cabeza a la izquierda y pies hacia la derecha.','contacts':'Espalda alta sostenida por una superficie elevada; pie o pies plantados delante del cuerpo, pelvis en contacto con la resistencia.','posture':'Torso y muslo de apoyo alineados arriba, rodilla doblada, tibia próxima a vertical y costillas recogidas.','load':'La resistencia empuja hacia abajo sobre la parte anterior de la pelvis mientras la cadera la eleva.'},
 'byImplement':{'barbell':{'geometry':'Banco horizontal firme bajo las escápulas inferiores, barra transversal acolchada sobre las caderas y manos agarrando el eje. Discos a ambos lados separados del suelo en la posición alta y pies planos delante del banco.'},'smith_machine':{'geometry':'Banco colocado dentro de una Smith completa de carriles verticales; barra acolchada guiada cruza la pelvis y sigue conectada a sus carros. Pies delante del banco y espalda alta sobre su borde, manos sujetando el eje.'},'band':{'geometry':'Banda larga sobre los pliegues de las caderas, tensada hacia dos anclajes bajos fijados a los laterales del rack. Banco estable tras los hombros, pies delante y manos sobre el tramo pélvico para evitar desplazamiento.'},'machine':{'geometry':'Estación de hip thrust con torre de pesas, plataforma fija delante de los pies, respaldo acolchado basculante bajo el tronco y rodillo transversal conectado al brazo de empuje sobre la pelvis. Ambas manos agarran las asas y el rodillo está elevado en contacto con las caderas.'}},
 'promptCore':{'barbell':'Oblique side view, frozen at the TOP of a barbell hip thrust. Lower shoulder blades press against the edge of a stable bench and both feet are flat on the floor in front. A padded loaded barbell rests across the hip creases; both hands grip its shaft beside the body. Torso and thighs are aligned, knees bent, shins nearly vertical and ribs low. Both plates are clear of the floor. No text or logos.','smith_machine':'Side view, frozen at the TOP of a hip thrust inside a complete vertical Smith machine. Upper back presses against a bench, both feet flat on the floor in front. The padded guided bar stays attached to both rail carriages and rests across the raised pelvis, held by both hands. Torso and thighs align, knees bent and ribs low; the loaded bar ends are clear of the floor. No text or logos.','band':'Oblique side view, frozen at the TOP of a band hip thrust. Shoulder blades press into a stable bench, both feet flat on the floor in front. One long resistance band is stretched across the raised hip creases to two fixed low pegs on opposite sides of a rack. Both hands hold the band against the pelvis. Torso and thighs align, knees bent, ribs low. The band is not around the knees. No text or logos.','machine':'Side view, frozen at the TOP of a selectorized hip thrust station. The athlete faces upward, back supported by the tilted padded backrest. Both feet press flat into the front platform. Both hands grip side handles. A padded transverse roller on the machine lever is pressed against the raised hip creases, never floating. Torso and thighs align, knees bent; the lever is linked to a real weight stack. No text or logos.'},
 'forbidden':['Espalda alta directamente en el suelo: corresponde al puente y no a este apoyo elevado.','Peso separado de la pelvis o rodillo flotando fuera del cuerpo.','Máquina inventada que combine cinturón, barra libre y rodillo como una sola resistencia.','Banda cerrada solo en los muslos con apertura resistida de rodillas: esa acción añadiría glúteo medio principal y no representa la banda pélvica anclada.','Dos pies en apoyo en una variante unilateral o un pie libre colocado sobre el activo.','Torso libre sin banco ni respaldo, o apoyo solo bajo el cuello.'],
 'qa':['¿La espalda alta está sostenida por un apoyo elevado o por el respaldo propio de la estación?','¿La pelvis se encuentra en la posición superior y el torso se alinea con el muslo de apoyo?','¿La resistencia toca las caderas y las manos agarran el eje, las asas o el tramo pélvico de la banda?','¿Se ve un pie activo en unilateral y dos en bilateral?','¿La banda pélvica se fija a dos anclajes bajos y no representa una abducción resistida de rodillas?','¿El mecanismo de máquina se muestra como una estación real con respaldo, plataforma y rodillo unidos al sistema de carga?'], 'byVariant':{}},
 'sources':[GM,HAM,CORE,MED,PELVIC,HIP,FOREARM,KENNEDY,BRAZIL,BRIDGE,EVOLUTION,UNILATERAL,PANATTA]}
for cid in thrust_configs:
 if '__unilateral__' in cid:
  thrust['anatomy']['overrides'][cid]={'muscles':[muscle('gluteus_medius','STABILIZER','El apoyo de un único pie exige sostener las hemipelvis a una altura parecida; su función frontal es isométrica, sin mover la pierna en abducción contra carga.','gmmed_anatomy','bridge_emg')],'joints':[joint('cadera','PRIMARY',['Extensión de cadera'],'Una sola cadera eleva la pelvis bajo la resistencia y el apoyo superior elevado; el lado de la pierna suspendida pierde el soporte inferior y requiere control frontal.','hip_joint','thrust_variations'),joint('sacroiliaca','STABILIZER',['Transferencia pélvica con apoyo unilateral'],'El anillo pélvico recibe el empuje desde un solo pie y lo transmite al respaldo o banco; el lado libre no debe aportar un segundo apoyo ni una torsión deliberada.','pelvic_joints','thrust_variations')]}
  thrust['visual']['byVariant'][cid]={'difference':'Solo un pie está plantado en el suelo o la plataforma de la estación; la pierna libre queda recogida y suspendida. Rodillo, banda o eje siguen tocando la pelvis, con ambas caderas a altura semejante.'}
for lat in ['bilateral','unilateral']:
 cid=f'hip_thrust__{lat}__band'
 over=thrust['anatomy']['overrides'].setdefault(cid,{'muscles':[],'joints':[]})
 over['joints']=[j for j in over.get('joints',[]) if j['id']!='cadera']+[joint('cadera','PRIMARY',['Extensión de cadera'],'La pelvis extiende contra una banda larga anclada por debajo y a ambos lados; su estiramiento crece al elevar las caderas, sin resistencia de apertura en las rodillas.','hip_joint','thrust_variations')]
 cid=f'hip_thrust__{lat}__machine'
 over=thrust['anatomy']['overrides'].setdefault(cid,{'muscles':[],'joints':[]})
 machine_why = 'Una sola cadera eleva el rodillo de empuje con un pie sobre la plataforma y el otro fuera de ella; el respaldo basculante sostiene el tronco y acompaña su cambio de inclinación.' if lat == 'unilateral' else 'La cadera eleva el rodillo de empuje con los pies sobre la plataforma; el respaldo basculante sostiene el tronco y acompaña su cambio de inclinación.'
 over['joints']=[j for j in over.get('joints',[]) if j['id']!='cadera']+[joint('cadera','PRIMARY',['Extensión de cadera'],machine_why,'hip_joint','thrust_machine')]
 over['muscles'].append(muscle('forearm','STABILIZER','Los dedos agarran las asas de la estación para fijar el cuerpo contra el respaldo durante el empuje; el rodillo, no las manos, carga la pelvis.','forearm_anatomy','thrust_machine'))
 cid=f'hip_thrust__{lat}__smith_machine'
 over=thrust['anatomy']['overrides'].setdefault(cid,{'muscles':[],'joints':[]})
 over['joints']=[j for j in over.get('joints',[]) if j['id']!='cadera']+[joint('cadera','PRIMARY',['Extensión de cadera'],'La pelvis empuja una barra limitada por los carriles de la Smith; la posición del banco respecto del eje organiza el arco de la cadera y el apoyo del pie.','hip_joint','thrust_variations')]

frog={'status':'CURATED','public':{'description':'Los Frog Pumps son un puente corto para el glúteo mayor con las plantas juntas y las rodillas abiertas. La pelvis sube desde el suelo entre una base estrecha de pies y la espalda alta apoyada, con las rodillas muy dobladas. El abdomen acompaña el sostén pélvico sin buscar un arco lumbar al final. La postura de cadera ya está abierta antes de empezar y no incluye una apertura contra resistencia. Su atractivo es repetir ese empuje con el propio cuerpo y sin preparar una carga externa.','configurations':{'glutes_frog_pumps__default':cfg('Las plantas permanecen enfrentadas y los bordes de los pies descansan en el suelo mientras sube la pelvis. Las rodillas conservan su apertura de partida; el peso del cuerpo es la resistencia del empuje, sin banda que obligue a separarlas.', ['Túmbate boca arriba y junta las plantas con los talones próximos a la pelvis.','Deja las rodillas abiertas y apoya la espalda alta y los codos en la colchoneta.'],['Eleva la pelvis sin cambiar la apertura de las rodillas.','Baja al suelo sin separar las plantas ni aumentar el arco lumbar.'])}},
 'anatomy':{'muscles':[muscle('gluteus_maximus','PRIMARY','Extiende las caderas para despegar la pelvis con los talones cercanos y las rodillas muy dobladas; la postura abierta por sí sola no convierte el gesto en una abducción resistida.','gm_anatomy','frog_demo'),muscle('core','STABILIZER','La pared abdominal sostiene la inclinación pélvica del puente corto y limita el arco lumbar al final; no produce una flexión repetida del tronco contra carga externa.','abdominal_wall','frog_demo')],'joints':[joint('cadera','PRIMARY',['Extensión de cadera'],'La extensión levanta la pelvis desde el suelo con una postura inicial de abducción y rotación externa; las rodillas no se abren más contra una carga durante la subida.','hip_joint','frog_demo'),joint('rodilla','STABILIZER',['Sostén en flexión marcada'],'La rodilla queda muy doblada para acercar los talones a la pelvis; el contacto de las plantas se conserva sin un curl que lleve el pie hacia atrás contra resistencia.','frog_demo','ham_anatomy'),joint('columna-lumbar','STABILIZER',['Control de la inclinación pélvica'],'La región lumbar no se arquea al alcanzar el punto alto; la posición pélvica acompaña el empuje de cadera sin transformar la repetición en extensión de la espalda.','abdominal_wall','frog_demo'),joint('sacroiliaca','STABILIZER',['Transmisión de fuerza con postura abierta'],'El anillo pélvico transmite el empuje de los pies enfrentados hacia la espalda apoyada; la apertura visible nace en las caderas y no en una separación sacroilíaca.','pelvic_joints','hip_joint')]},
 'technique':{'identity':'Puente supino desde el suelo con plantas juntas, bordes de los pies apoyados y rodillas abiertas en abducción y rotación externa. La pelvis asciende con rodillas muy flexionadas y el ángulo de apertura se conserva, sin una resistencia externa que cierre las rodillas.','setup':['Colchoneta en el suelo, espalda alta apoyada, codos doblados apoyados junto al cuerpo y cabeza en posición cómoda.','Plantas de ambos pies juntas, talones próximos a la pelvis y rodillas abiertas dentro de la posición disponible, sin forzar el ancho.'],'keyPositions':['Abajo: pelvis sobre la colchoneta, plantas enfrentadas y rodillas abiertas, con contacto de los bordes externos de los pies en el suelo.','Arriba: pelvis elevada, espalda alta y codos todavía apoyados, pies juntos y la misma apertura de rodillas; las costillas no se proyectan hacia el techo.'],'mistakes':['Separar los pies y apoyar ambas plantas planas como en un puente de apoyo paralelo.','Añadir una apertura repetida de rodillas contra resistencia externa.','Levantar los hombros del suelo o arquear la espalda para aumentar la altura final.','Mover los talones lejos de la pelvis y perder la flexión marcada de rodillas.'],'phases':[phase('Empuje de cadera','La pelvis deja el suelo mientras las plantas siguen enfrentadas y los bordes de los pies sirven de apoyo, sin abrir más las rodillas.'),phase('Punto alto corto','La extensión de cadera alcanza su posición alta sin arco lumbar adicional; espalda alta y codos siguen sobre la colchoneta.'),phase('Vuelta al apoyo','La pelvis retorna al suelo con la postura abierta intacta y sin separar los pies entre repeticiones.')]},
 'visual':{'base':{'camera':'Vista lateral oblicua desde el extremo de los pies para mostrar simultáneamente plantas juntas y rodillas abiertas.','phase':'Pelvis elevada en el punto superior del puente corto, con postura abierta ya fijada.','orientation':'Atleta boca arriba sobre una colchoneta, hombros en el suelo y pies cercanos a la pelvis.','contacts':'Espalda alta y codos en el suelo; plantas enfrentadas entre sí y bordes externos de los pies sobre la colchoneta.','posture':'Rodillas muy dobladas y abiertas, pelvis elevada, costillas bajas y región lumbar sin arco exagerado.','load':'El propio cuerpo constituye la carga del empuje pélvico, sin peso añadido.'},'byImplement':{'bodyweight':{'geometry':'Atleta sobre colchoneta con codos apoyados junto a los costados; plantas juntas y talones cercanos a la pelvis. Rodillas abiertas en posición de mariposa y pelvis levantada sin carga ni banda.'}},'promptCore':{'bodyweight':'Oblique side view from near the feet, frozen at the TOP of a bodyweight frog pump on a floor mat. Upper back and both bent elbows press into the mat. Soles touch each other and outer foot edges contact the mat, heels close to the pelvis. Knees are deeply bent and open in a butterfly position. The pelvis is raised, ribs low, no excessive lumbar arch. No external load or band; hands hold no weight. No text or logos.'},'forbidden':['Pies separados con las dos plantas planas en el suelo y rodillas paralelas.','Espalda alta sobre un banco: ese apoyo corresponde a un frog thrust.','Banda en las rodillas o apertura resistida añadida: requeriría declarar el glúteo medio principal para esa acción y ya no es la configuración corporal asignada.','Peso externo flotando sobre la pelvis o manos sujetando una mancuerna en el montaje corporal.'],'qa':['¿Las plantas de los pies están juntas y las rodillas abiertas?','¿La pelvis está elevada en el fotograma superior con la espalda alta en el suelo?','¿Los bordes de los pies y los codos están apoyados, sin una carga externa sin sujeción?','¿La imagen carece de una banda o mecanismo que resista la apertura de rodillas?']},'sources':[GM,CORE,PELVIC,HIP,HAM,FROG]}

reverse={'status':'CURATED','public':{'description':'El Reverse Hyper mueve las piernas para trabajar el glúteo mayor y los isquiosurales desde una plataforma acolchada que sostiene el tronco. Un péndulo unido a los pies recorre un arco bajo el aparato mientras las manos agarran las asas del extremo delantero. La pelvis acompaña a las piernas y la musculatura lumbar también participa; el apoyo superior no fija toda la espalda. El regreso pasa por debajo de las caderas antes del siguiente empuje. Permite cargar la extensión de cadera sin sujetar el peso con los brazos.','configurations':{'reverse_hyper__machine':cfg('La correa conecta ambos pies con el brazo pendular situado bajo la plataforma. El torso descansa boca abajo sobre el acolchado, pero la pelvis conserva movimiento en el borde; las asas fijan la parte superior del cuerpo.', ['Ajusta la correa del péndulo a ambos pies y coloca el pecho y el abdomen sobre el acolchado.','Deja las caderas cerca del borde posterior y agarra las dos asas delanteras.'],['Eleva las piernas hasta aproximarlas a la línea del torso sin levantar el pecho.','Devuelve las piernas bajo la plataforma sin lanzar el péndulo.'])}},
 'anatomy':{'muscles':[muscle('gluteus_maximus','PRIMARY','Eleva las piernas al extender las caderas contra el brazo pendular; su actividad está medida en la máquina real y se conserva como dominante del gesto extensor.','rhe_load','gm_anatomy'),muscle('hamstrings','SECONDARY','Las porciones que cruzan la cadera acompañan la elevación de las piernas; el bíceps femoral aumenta su actividad con la carga del péndulo sin que haya un curl programado.','rhe_load','ham_anatomy'),muscle('erector_spinae','SECONDARY','El acolchado sostiene pecho y abdomen, pero no inmoviliza la relación pelvis-tronco: el estudio midió movimiento y momento lumbar. Participa en ese componente, sin ser el motor dominante de las piernas.','rhe_biomechanics','rhe_load'),muscle('forearm','STABILIZER','Las manos agarran las asas para fijar el cuerpo sobre la plataforma mientras las piernas desplazan el péndulo; los flexores de dedos sostienen ese agarre de apoyo.','forearm_anatomy','rhe_machine')],'joints':[joint('cadera','PRIMARY',['Extensión de cadera'],'Las piernas pasan desde debajo del cuerpo hacia la línea del tronco contra el péndulo; el apoyo superior permite ese arco de muslo respecto de pelvis sin elevar el tórax.','rhe_biomechanics','rhe_load'),joint('columna-lumbar','SECONDARY',['Flexión y extensión lumbopélvica'],'La pelvis se mueve en el borde de la plataforma y cambia su relación con el tronco apoyado; Lawrence midió movilidad y momento lumbar reales, que no equivalen a una columna inmóvil.','rhe_biomechanics','rhe_load'),joint('rodilla','STABILIZER',['Sostén de la longitud de las piernas'],'Las rodillas permanecen casi extendidas mientras la correa mueve los pies por el arco; su función es sostener la longitud de la palanca y no doblarse para traccionar el péndulo.','rhe_machine','ham_anatomy'),joint('muñeca','STABILIZER',['Sostén del agarre de apoyo'],'Cada mano conserva el contacto con un asa fija para que el péndulo no arrastre el cuerpo sobre el acolchado; la muñeca no mueve la resistencia.','forearm_anatomy','rhe_machine'),joint('sacroiliaca','STABILIZER',['Transmisión pélvica hacia el torso apoyado'],'La fuerza de las piernas llega al anillo pélvico y se transmite al tronco sostenido; el movimiento lumbo-pélvico observado no demuestra una excursión sacroilíaca voluntaria.','pelvic_joints','rhe_biomechanics')]},
 'technique':{'identity':'Extensión de cadera en decúbito prono sobre una plataforma elevada con pecho y abdomen apoyados, caderas cerca del borde y ambas piernas libres. Una correa para los pies conecta las piernas al péndulo inferior, y las manos agarran asas fijas; la pelvis puede acompañar el arco sin que se despegue el pecho.','setup':['Máquina Reverse Hyper real con plataforma acolchada horizontal, asas delanteras y péndulo bajo la plataforma con postes de discos.','Correa conectada al péndulo alrededor de ambos pies, pecho y abdomen sostenidos sobre el tablero y caderas en su borde posterior.','Las manos agarran las asas por delante, piernas juntas y rodillas casi extendidas con los pies suspendidos.'],'keyPositions':['Abajo: piernas bajo las caderas, péndulo suspendido bajo el aparato y pelvis cerca del borde, con pecho sobre el acolchado.','Arriba: piernas aproximadamente en la línea horizontal del torso, manos en las asas y correa tensa conectada al péndulo.','El apoyo es de pecho y abdomen; el borde no inmoviliza la región lumbo-pélvica ni justifica dibujar un torso libre.'],'mistakes':['Levantar el pecho y el abdomen fuera de la plataforma para mover el peso.','Dibujar o usar la correa separada de los pies o desconectada del péndulo.','Lanzar las piernas muy por encima de la línea del cuerpo con un arco lumbar exagerado.','Doblar las rodillas para convertir el arco en un curl de piernas.'],'phases':[phase('Elevación de piernas','Los extensores de cadera llevan las piernas atrás y arriba contra el péndulo; el apoyo superior queda en contacto y la pelvis acompaña el arco.'),phase('Límite superior','Las piernas llegan aproximadamente a la línea del torso con la correa tensa, sin levantar el pecho ni prolongar la altura por un latigazo lumbar.'),phase('Retorno pendular','Las piernas vuelven por debajo de las caderas junto al brazo de carga; el tronco permanece sostenido y las manos conservan el agarre.')]},
 'visual':{'base':{'camera':'Vista lateral ligeramente oblicua con la plataforma, ambas asas, las piernas y el péndulo íntegros.','phase':'Piernas en el punto alto del arco, aproximadamente a la altura horizontal del torso.','orientation':'Atleta boca abajo con cabeza hacia el extremo delantero de la plataforma y piernas fuera del borde posterior.','contacts':'Pecho y abdomen sostenidos por el acolchado, manos agarrando asas fijas y correa rodeando ambos pies.','posture':'Torso sobre la plataforma, pelvis en el borde y piernas juntas casi rectas alineadas con el cuerpo, sin arco lumbar exagerado.','load':'Péndulo bajo la plataforma conectado a ambos pies mediante la correa, con discos sobre sus postes y separados del suelo.'},'byImplement':{'machine':{'geometry':'Plataforma horizontal alta sobre un bastidor, asas fijas en el extremo delantero y pivote pendular bajo el tablero. Un brazo cargado con discos queda por debajo de la plataforma; una correa une sus postes al apoyo de ambos pies, elevada atrás con las piernas en el fotograma alto.'}},'promptCore':{'machine':'Oblique side view, frozen at the TOP of a real reverse hyper machine. The athlete lies face down with chest and abdomen pressed onto a high horizontal padded platform, hips at its rear edge. Both hands grip the fixed front handles. Both legs extend behind, nearly straight and roughly level with the torso. A taut foot strap connects both feet to the loaded pendulum below the platform. The pendulum plates remain below the pad and clear of the floor. No text or logos.'},'forbidden':['Atleta con torso libre o pecho despegado de la plataforma, como una extensión de espalda.','Correa desconectada del péndulo o carga flotante sin vínculo con los pies.','Péndulo con discos situado por encima del tablero o agarrado con las manos.','Piernas muy por encima del torso y zona lumbar arqueada de forma exagerada.','Apoyo torácico convertido en férula que inmoviliza toda la pelvis: no representa el movimiento lumbo-pélvico de la máquina estudiada.'],'qa':['¿El pecho y el abdomen están sostenidos por el acolchado horizontal?','¿Las dos manos agarran las asas fijas del extremo delantero?','¿Las piernas están en el punto alto aproximadamente alineadas con el torso?','¿La correa rodea ambos pies y se conecta al péndulo cargado bajo la plataforma?','¿El tronco sigue apoyado y la pelvis queda en el borde, sin un soporte que la inmovilice?']},'sources':[GM,HAM,PELVIC,FOREARM,RHE19,RHE22,ROGUE]}

QUADS=source('quadriceps_anatomy','30020706','El cuádriceps produce extensión de rodilla; el puente con los pies fijos incluye un cambio menor del ángulo de esa articulación durante la elevación pélvica.')
bridge['sources'].append(QUADS)
bridge['anatomy']['muscles'].insert(2,muscle('quadriceps','SECONDARY','Ayuda a la demanda extensora de rodilla asociada al apoyo de los pies y al ascenso pélvico; su señal se registró en el puente con barra. Se extrapola la función al resto de montajes, sin igualar su activación a la de cadera.','quadriceps_anatomy','bridge_thrust_emg'))
bridge['anatomy']['joints'][1]=joint('rodilla','SECONDARY',['Extensión de rodilla asociada al ascenso'],'Con el pie plantado, el ángulo de rodilla acompaña el ascenso de la pelvis y la rotación del muslo. Su participación es menor que la extensión de cadera y no constituye un curl.','quadriceps_anatomy','floor_bridge_demo','bridge_thrust_emg')
bridge['anatomy']['joints'].append(joint('muñeca','STABILIZER',['Sujeción de la carga pélvica'],'La mano conserva su posición sobre el peso para impedir que ruede por las caderas; la muñeca sirve al agarre y no desplaza la resistencia como un levantamiento de brazos.','forearm_anatomy','bridge_demonstrations'))
bridge['anatomy']['overrides']['glutes_puente_gluteos__bilateral__bodyweight']['joints'].append({'id':'muñeca','role':'NONE','why':'Las manos descansan junto al cuerpo sin agarrar peso ni transmitir el sostén del cuerpo por las muñecas.'})
bridge['public']['description']='El Puente de Glúteos desarrolla la extensión de cadera con el glúteo mayor como motor, acompañado por isquiosurales y cuádriceps. La espalda alta descansa en el suelo mientras la pelvis se eleva entre los hombros y los pies, con un recorrido más corto que el apoyo elevado. El abdomen estabiliza el tronco para que la subida nazca en las caderas. Una pierna libre añade demanda de sostén pélvico. Es una forma de cargar la extensión de cadera desde una posición baja y con apoyos definidos.'
thrust['anatomy']['joints'].append(joint('muñeca','STABILIZER',['Agarre del contacto de resistencia'],'El eje libre o guiado, el tramo pélvico de la banda o las asas de la estación necesitan sujeción; la muñeca transmite esa fijación sin generar el empuje pélvico.','forearm_anatomy','thrust_variations','thrust_machine'))
DB_SINGLE=page('dumbbell_single_bridge','https://www.pt2austin.com/movement-library/single-leg-dumbbell-glute-bridge','Single Leg Dumbbell Glute Bridge','La biblioteca original del entrenador describe un pie plantado, el opuesto libre y una mancuerna sujeta sobre la cadera de apoyo; se usa solo para comprobar el montaje.')
bridge['sources'].append(DB_SINGLE)
bridge['anatomy']['overrides']['glutes_puente_gluteos__unilateral__dumbbells']['joints'][0]['sources'].append('dumbbell_single_bridge')

def replace_text(value,changes):
 if isinstance(value,str):
  for old,new in changes.items(): value=value.replace(old,new)
  return value
 if isinstance(value,list): return [replace_text(v,changes) for v in value]
 if isinstance(value,dict): return {k:replace_text(v,changes) for k,v in value.items()}
 return value
reverse=replace_text(reverse,{'unido a los pies':'unido a los tobillos','conecta ambos pies':'conecta ambos tobillos','a ambos pies':'a ambos tobillos','para los pies conecta':'para los tobillos conecta','alrededor de ambos pies':'alrededor de ambos tobillos','los pies mediante la correa':'los tobillos mediante la correa','al apoyo de ambos pies':'al apoyo de ambos tobillos','correa rodeando ambos pies':'correa rodeando ambos tobillos','correa rodea ambos pies':'correa rodea ambos tobillos','correa separada de los pies':'correa separada de los tobillos','vínculo con los pies':'vínculo con los tobillos','both feet to the loaded pendulum':'both ankles to the loaded pendulum','both feet to the loaded':'both ankles to the loaded','foot strap connects both feet':'ankle strap connects both ankles'})
bodies={'glutes_puente_gluteos':bridge,'hip_thrust':thrust,'glutes_frog_pumps':frog,'reverse_hyper':reverse}
changed=[]
for p in sorted((PRIVATE/'fichas').glob('*.json')):
 data=json.loads(p.read_text(encoding='utf-8'))
 for did in bodies:
  if did in data.get('definitions',{}): data['definitions'][did]=bodies[did];changed.append(did)
 if any(did in data.get('definitions',{}) for did in bodies):
  p.write_text(json.dumps(data,ensure_ascii=False,sort_keys=True,indent=2)+'\n',encoding='utf-8',newline='\n')
assert sorted(changed)==sorted(bodies)
print('Private author B: bodies',','.join(changed),'configurations',sum(len(b['public']['configurations']) for b in bodies.values()))
