package com.example.kpkn.data.repository

import android.content.Context
import com.example.kpkn.data.db.KpknDatabase
import com.example.kpkn.data.db.toCompetitionRecord
import com.example.kpkn.data.db.toEntity
import com.example.kpkn.data.models.CompetitionRecord
import com.example.kpkn.data.models.CompetitionRecordStatus
import com.example.kpkn.services.competition.CompetitionReminderManager
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * Single source of truth for competition records.
 *
 * Competitions are historical/planned events, not workout sessions by default.
 * A record may be technical, journal-style, or hybrid and can optionally link
 * back to a planned competition session generated by a program key date.
 */
class CompetitionRepository private constructor(context: Context) {

    private val db = KpknDatabase.getInstance(context)
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val reminderManager = CompetitionReminderManager(context)

    private val _records = MutableStateFlow<List<CompetitionRecord>>(emptyList())
    val records: StateFlow<List<CompetitionRecord>> = _records.asStateFlow()

    init {
        scope.launch {
            val persisted = db.competitionRecordDao().getAll().map { it.toCompetitionRecord() }
            _records.value = persisted.sortedWith(recordSorter)
        }
    }

    fun getById(id: String): CompetitionRecord? =
        _records.value.firstOrNull { it.id == id }

    fun getByPlannedSessionId(sessionId: String): CompetitionRecord? =
        _records.value.firstOrNull { it.plannedSessionId == sessionId }

    fun activeCompetitionExerciseIds(): Set<String> =
        competitionExerciseIds(_records.value.filterNot { it.status == CompetitionRecordStatus.ARCHIVED })

    fun upsert(record: CompetitionRecord) {
        val normalized = record.withFreshTimestamps()
        _records.update { current ->
            val next = if (current.any { it.id == normalized.id }) {
                current.map { if (it.id == normalized.id) normalized else it }
            } else {
                current + normalized
            }
            next.sortedWith(recordSorter)
        }
        scope.launch { db.competitionRecordDao().upsert(normalized.toEntity()) }
        reminderManager.schedule(normalized)
    }

    suspend fun upsertNow(record: CompetitionRecord) {
        val normalized = record.withFreshTimestamps()
        _records.update { current ->
            val next = if (current.any { it.id == normalized.id }) {
                current.map { if (it.id == normalized.id) normalized else it }
            } else {
                current + normalized
            }
            next.sortedWith(recordSorter)
        }
        withContext(Dispatchers.IO) { db.competitionRecordDao().upsert(normalized.toEntity()) }
        reminderManager.schedule(normalized)
    }

    fun delete(id: String) {
        _records.update { it.filterNot { record -> record.id == id } }
        scope.launch { db.competitionRecordDao().delete(id) }
        reminderManager.cancel(id)
    }

    private fun CompetitionRecord.withFreshTimestamps(): CompetitionRecord {
        val now = System.currentTimeMillis()
        return copy(
            createdAtMs = if (createdAtMs > 0L) createdAtMs else now,
            updatedAtMs = now,
        )
    }

    companion object {
        @Volatile private var INSTANCE: CompetitionRepository? = null

        private val recordSorter = compareByDescending<CompetitionRecord> { it.eventDate.orEmpty() }
            .thenByDescending { it.updatedAtMs }

        fun init(context: Context): CompetitionRepository =
            INSTANCE ?: synchronized(this) {
                INSTANCE ?: CompetitionRepository(context.applicationContext).also { INSTANCE = it }
            }

        fun getInstance(): CompetitionRepository =
            INSTANCE ?: error("CompetitionRepository not initialized - call init(context) first.")

        fun competitionExerciseIds(records: List<CompetitionRecord>): Set<String> =
            records
                .flatMap { record -> record.technicalBlocks }
                .mapNotNull { block -> block.canonicalExerciseId ?: block.exerciseDbId }
                .filter { it.isNotBlank() }
                .toSet()
    }
}
