/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './index.tsx',
    './components/**/*.{tsx,ts,jsx,js}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary-color)',
        cyber: {
          canvas: '#0A0B0E',
          card: '#15171E',
          border: '#2A2D38',
          cyan: '#00F0FF',
          copper: '#FF7B00',
          success: '#00FF9D',
          warning: '#FFD600',
          danger: '#FF2E43',
        },
        // ── Material You tokens (generados dinámicamente por tema engine) ──
        md: {
          primary: 'var(--md-sys-color-primary)',
          'on-primary': 'var(--md-sys-color-on-primary)',
          'primary-container': 'var(--md-sys-color-primary-container)',
          'on-primary-container': 'var(--md-sys-color-on-primary-container)',
          secondary: 'var(--md-sys-color-secondary)',
          'on-secondary': 'var(--md-sys-color-on-secondary)',
          'secondary-container': 'var(--md-sys-color-secondary-container)',
          'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
          tertiary: 'var(--md-sys-color-tertiary)',
          'on-tertiary': 'var(--md-sys-color-on-tertiary)',
          'tertiary-container': 'var(--md-sys-color-tertiary-container)',
          'on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
          error: 'var(--md-sys-color-error)',
          'error-container': 'var(--md-sys-color-error-container)',
          background: 'var(--md-sys-color-background)',
          'on-background': 'var(--md-sys-color-on-background)',
          surface: 'var(--md-sys-color-surface)',
          'on-surface': 'var(--md-sys-color-on-surface)',
          'surface-variant': 'var(--md-sys-color-surface-variant)',
          'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
          'surface-container': 'var(--md-sys-color-surface-container)',
          'surface-container-high': 'var(--md-sys-color-surface-container-high)',
          outline: 'var(--md-sys-color-outline)',
          'outline-variant': 'var(--md-sys-color-outline-variant)',
        },
        // ── KPKN semánticos derivados del tema ────────────────────────────
        kpkn: {
          'battery-high': 'var(--kpkn-battery-high)',
          'battery-mid': 'var(--kpkn-battery-mid)',
          'battery-low': 'var(--kpkn-battery-low)',
          'ring-cns': 'var(--kpkn-ring-cns)',
          'ring-muscular': 'var(--kpkn-ring-muscular)',
          'ring-spinal': 'var(--kpkn-ring-spinal)',
        },
      },
      fontFamily: {
        sans: ['var(--md-sys-typescale-font-family-plain)', 'system-ui', 'sans-serif'],
        mono: ['var(--md-sys-typescale-font-family-data)', 'ui-monospace', 'monospace'],
        brand: ['var(--md-sys-typescale-font-family-brand)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        // M3 Type Scale (usables como text-display-lg, text-body-md, etc.)
        'display-lg': ['var(--md-sys-typescale-display-large-size)', { lineHeight: 'var(--md-sys-typescale-display-large-line-height)', fontWeight: 'var(--md-sys-typescale-display-large-weight)' }],
        'display-md': ['var(--md-sys-typescale-display-medium-size)', { lineHeight: 'var(--md-sys-typescale-display-medium-line-height)', fontWeight: 'var(--md-sys-typescale-display-medium-weight)' }],
        'display-sm': ['var(--md-sys-typescale-display-small-size)', { lineHeight: 'var(--md-sys-typescale-display-small-line-height)', fontWeight: 'var(--md-sys-typescale-display-small-weight)' }],
        'headline-lg': ['var(--md-sys-typescale-headline-large-size)', { lineHeight: 'var(--md-sys-typescale-headline-large-line-height)', fontWeight: 'var(--md-sys-typescale-headline-large-weight)' }],
        'headline-md': ['var(--md-sys-typescale-headline-medium-size)', { lineHeight: 'var(--md-sys-typescale-headline-medium-line-height)', fontWeight: 'var(--md-sys-typescale-headline-medium-weight)' }],
        'headline-sm': ['var(--md-sys-typescale-headline-small-size)', { lineHeight: 'var(--md-sys-typescale-headline-small-line-height)', fontWeight: 'var(--md-sys-typescale-headline-small-weight)' }],
        'title-lg': ['var(--md-sys-typescale-title-large-size)', { lineHeight: 'var(--md-sys-typescale-title-large-line-height)', fontWeight: 'var(--md-sys-typescale-title-large-weight)' }],
        'title-md': ['var(--md-sys-typescale-title-medium-size)', { lineHeight: 'var(--md-sys-typescale-title-medium-line-height)', fontWeight: 'var(--md-sys-typescale-title-medium-weight)' }],
        'title-sm': ['var(--md-sys-typescale-title-small-size)', { lineHeight: 'var(--md-sys-typescale-title-small-line-height)', fontWeight: 'var(--md-sys-typescale-title-small-weight)' }],
        'body-lg': ['var(--md-sys-typescale-body-large-size)', { lineHeight: 'var(--md-sys-typescale-body-large-line-height)', fontWeight: 'var(--md-sys-typescale-body-large-weight)' }],
        'body-md': ['var(--md-sys-typescale-body-medium-size)', { lineHeight: 'var(--md-sys-typescale-body-medium-line-height)', fontWeight: 'var(--md-sys-typescale-body-medium-weight)' }],
        'body-sm': ['var(--md-sys-typescale-body-small-size)', { lineHeight: 'var(--md-sys-typescale-body-small-line-height)', fontWeight: 'var(--md-sys-typescale-body-small-weight)' }],
        'label-lg': ['var(--md-sys-typescale-label-large-size)', { lineHeight: 'var(--md-sys-typescale-label-large-line-height)', fontWeight: 'var(--md-sys-typescale-label-large-weight)' }],
        'label-md': ['var(--md-sys-typescale-label-medium-size)', { lineHeight: 'var(--md-sys-typescale-label-medium-line-height)', fontWeight: 'var(--md-sys-typescale-label-medium-weight)' }],
        'label-sm': ['var(--md-sys-typescale-label-small-size)', { lineHeight: 'var(--md-sys-typescale-label-small-line-height)', fontWeight: 'var(--md-sys-typescale-label-small-weight)' }],
      },
      borderRadius: {
        // M3 Shape Scale
        'none': 'var(--md-sys-shape-corner-none, 0px)',
        'xs': 'var(--md-sys-shape-corner-extra-small, 4px)',
        'sm': 'var(--md-sys-shape-corner-small, 8px)',
        'md': 'var(--md-sys-shape-corner-medium, 12px)',
        'lg': 'var(--md-sys-shape-corner-large, 16px)',
        'xl': 'var(--md-sys-shape-corner-extra-large, 24px)',
        'full': 'var(--md-sys-shape-corner-full, 9999px)',
      },
    },
  },
  plugins: [],
};
