package com.example.kpkn.screens.sessioneditor.components

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Test

class ExerciseCatalogV2LabelsTest {
    @Test
    fun controlledAxesAndOptionsAreLocalizedAtTheUiBoundary() {
        assertEquals("Implemento", exerciseCatalogAxisLabel("implement"))
        assertEquals("Estación", exerciseCatalogAxisLabel("station"))
        assertEquals("Ángulo y soporte", exerciseCatalogAxisLabel("support_angle"))
        assertEquals("Mancuerna", exerciseCatalogOptionLabel("dumbbells"))
        assertEquals("Máquina", exerciseCatalogOptionLabel("machine"))
        assertEquals("Polea", exerciseCatalogOptionLabel("cable"))
        assertEquals("Pec deck inverso", exerciseCatalogOptionLabel("pec_deck_reverse"))
        assertEquals("De pie", exerciseCatalogOptionLabel("standing"))
        assertEquals("Convencional", exerciseCatalogOptionLabel("conventional"))
        assertEquals("Sentado en máquina", exerciseCatalogOptionLabel("seated_machine"))
        assertEquals("Tumbado en máquina", exerciseCatalogOptionLabel("lying_machine"))
        assertEquals("De pie en polea", exerciseCatalogOptionLabel("standing_cable"))
        assertEquals("Barra a la espalda", exerciseCatalogOptionLabel("barbell_back"))
        assertEquals("B-stance (apoyo asimétrico)", exerciseCatalogOptionLabel("b_stance"))
        assertEquals("Postura", exerciseCatalogAxisLabel("stance"))
        assertEquals("Apoyo de piernas", exerciseCatalogAxisLabel("stance", definitionId = "romanian_deadlift"))
        assertEquals("Tipo de agarre", exerciseCatalogAxisLabel("grip_type"))
        assertEquals("Amplitud de agarre", exerciseCatalogAxisLabel("grip_width"))
        assertEquals("Altura de polea", exerciseCatalogAxisLabel("pulley_height"))
        assertEquals("Prono", exerciseCatalogOptionLabel("pronated"))
        assertEquals("Supino", exerciseCatalogOptionLabel("supinated"))
        assertEquals("Amplio", exerciseCatalogOptionLabel("wide"))
        assertEquals("Medio", exerciseCatalogOptionLabel("medium"))
        assertEquals("Cerrado", exerciseCatalogOptionLabel("close"))
        assertEquals("Alta", exerciseCatalogOptionLabel("high"))
        assertEquals("Media", exerciseCatalogOptionLabel("mid"))
        assertEquals("Baja", exerciseCatalogOptionLabel("low"))
        assertEquals("Máquina Convergente", exerciseCatalogEquipmentLabel("machine", definitionId = "bench_press"))
        assertEquals("Máquina Convergente", exerciseCatalogEquipmentLabel("machine", definitionId = "incline_bench_press"))
        assertEquals("Máquina Convergente", exerciseCatalogEquipmentLabel("machine", definitionId = "decline_bench_press"))
        assertEquals("Máquina", exerciseCatalogEquipmentLabel("machine", definitionId = "conventional_row"))
        assertEquals("Barra", exerciseCatalogEquipmentLabel("barbell", definitionId = "bench_press"))
        assertEquals("Con Barra", exerciseCatalogVariantTagLabel("barbell"))
        assertEquals("Con Mancuernas", exerciseCatalogVariantTagLabel("dumbbells"))
        assertEquals("En Smith", exerciseCatalogVariantTagLabel("smith_machine"))
        assertEquals("En Máquina", exerciseCatalogVariantTagLabel("machine"))
        assertEquals("En Polea", exerciseCatalogVariantTagLabel("cable"))
        assertEquals("Peso Corporal", exerciseCatalogVariantTagLabel("bodyweight"))
        assertEquals("Prono", exerciseCatalogVariantTagLabel("pronated"))
        assertEquals("Polea Alta", exerciseCatalogOptionLabel("cable", definitionId = "triceps_pushdown"))
        assertEquals("Polea", exerciseCatalogOptionLabel("cable"))
        assertEquals("Máquina Pec Deck", exerciseCatalogOptionLabel("machine", definitionId = "reverse_pec_fly"))
        assertEquals("Polea", exerciseCatalogAxisLabel("pulley_height", definitionId = "tren_superior_cruce_poleas"))
        assertEquals("Altura de polea", exerciseCatalogAxisLabel("pulley_height"))
        assertEquals("Polea Alta", exerciseCatalogOptionLabel("high", definitionId = "tren_superior_cruce_poleas"))
        assertEquals("Polea Baja", exerciseCatalogOptionLabel("low", definitionId = "tren_superior_cruce_poleas"))
        assertEquals("Barra de Seguridad", exerciseCatalogOptionLabel("safety_bar"))
        assertEquals("Con Barra de Seguridad", exerciseCatalogVariantTagLabel("safety_bar"))
        assertEquals("Barra H", exerciseCatalogOptionLabel("h_bar"))
        assertEquals("Con Barra H", exerciseCatalogVariantTagLabel("h_bar"))
        assertEquals("Glúteo Medio", exerciseCatalogMuscleLabel("gluteus_medius"))
        assertFalse(exerciseCatalogOptionLabel("dumbbells").equals("dumbbells", ignoreCase = true))
    }
}
