const fs = require("fs");
function L(id,nm,desc,musc,subM,cat,typ,eq,frc,bp,chn,st,td,efc,cnc,ssc){
  return "  { id: '"+id+"', name: '"+nm+"', description: '"+desc+"', involvedMuscles: [{ muscle: '"+musc+"', role: 'primary', activation: 1.0 }], subMuscleGroup: '"+subM+"', category: '"+cat+"', type: '"+typ+"', equipment: '"+eq+"', force: '"+frc+"', bodyPart: '"+bp+"', chain: '"+chn+"', setupTime: "+st+", technicalDifficulty: "+td+", efc: "+efc+", cnc: "+cnc+", ssc: "+ssc+" }";
}
function ex(id,nm,desc,musc,subM,cat,typ,eq,frc,bp,chn,st,td,efc,cnc,ssc){ return [id,nm,desc,musc,subM,cat,typ,eq,frc,bp,chn,st,td,efc,cnc,ssc]; }
const EX = [];// Barras
const BB = [
  ex("bb_ez_bench","Press Banca EZ","Press horizontal barra EZ","Pectoral Medio","Pectoral Medio","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,4,3.0,2.5,0.0),
  ex("bb_camber_incline","Press Inclinado Camber","Inclinado barra camber","Pectoral Superior","Pectoral Superior","Hipertrofia","Basico","Barra","Empuje","upper","anterior",4,5,3.2,2.8,0.0),
  ex("bb_decline_wide","Press Declinado Ancho","Declinado agarre amplio","Pectoral Inferior","Pectoral Inferior","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,4,3.0,2.5,0.0),
  ex("bb_front_squat_high","Sentadilla Frontal Alta","Front squat barra alta","Cuadriceps","Cuadriceps","Fuerza","Basico","Barra","Sentadilla","lower","anterior",4,6,3.5,3.0,0.5),
  ex("bb_safety_squat","Sentadilla Safety Bar","Squat barra seguridad","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Barra","Sentadilla","lower","anterior",4,5,3.5,2.8,0.5),
  ex("bb_zercher_squat","Sentadilla Zercher","Squat barra en codos","Cuadriceps","Cuadriceps","Fuerza","Basico","Barra","Sentadilla","lower","anterior",5,7,3.5,3.0,0.3),
  ex("bb_snatch_deadlift","Peso Muerto Snatch","Deadlift agarre snatch","Espalda Baja","Espalda Baja","Fuerza","Basico","Barra","Bisagra","lower","posterior",4,7,3.8,3.2,0.2),
  ex("bb_deficit_deadlift","Peso Muerto Deficit","Deadlift desde elevacion","Espalda Baja","Espalda Baja","Fuerza","Basico","Barra","Bisagra","lower","posterior",4,6,3.5,3.0,0.2),
  ex("bb_rack_pull_high","Rack Pull Alto","Peso muerto soportes altos","Espalda Baja","Espalda Baja","Fuerza","Accesorio","Barra","Bisagra","lower","posterior",3,5,3.5,3.0,0.0),
  ex("bb_rack_pull_low","Rack Pull Bajo","Peso muerto soportes bajos","Espalda Baja","Espalda Baja","Fuerza","Accesorio","Barra","Bisagra","lower","posterior",3,5,3.5,3.0,0.2),
  ex("bb_rdl_stiff","RDL Rigido","RDL rodillas rigidas","Isquiosurales","Isquiosurales","Hipertrofia","Basico","Barra","Bisagra","lower","posterior",3,5,3.2,2.5,0.3),
  ex("bb_bent_row_reverse","Remo Inclinado Inverso","Remo agarre supino","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Barra","Tiron","upper","posterior",4,5,3.2,2.5,0.2),
  ex("bb_upright_wide","Remo Menton Ancho","Remo vertical ancho","Trapecio","Trapecio","Hipertrofia","Accesorio","Barra","Tiron","upper","anterior",2,4,2.2,1.8,0.0),
  ex("bb_upright_narrow","Remo Menton Cerrado","Remo vertical cerrado","Deltoides Lateral","Deltoides Lateral","Hipertrofia","Accesorio","Barra","Tiron","upper","anterior",2,4,2.2,1.8,0.0),
  ex("bb_shrug_behind","Encogimiento Atras","Encogimiento barra atras","Trapecio","Trapecio","Hipertrofia","Aislamiento","Barra","Tiron","upper","posterior",3,4,2.0,1.5,0.0),
  ex("bb_shrug_front","Encogimiento Frente","Encogimiento barra frente","Trapecio","Trapecio","Hipertrofia","Aislamiento","Barra","Tiron","upper","posterior",2,2,2.0,1.5,0.0),
  ex("bb_ez_curl_wide","Curl EZ Ancho","Curl barra EZ ancho","Biceps","Biceps","Hipertrofia","Aislamiento","Barra","Tiron","upper","anterior",2,3,1.8,1.5,0.0),
  ex("bb_ez_curl_close","Curl EZ Cerrado","Curl barra EZ cerrado","Biceps","Biceps","Hipertrofia","Aislamiento","Barra","Tiron","upper","anterior",2,3,1.8,1.5,0.0),
  ex("bb_lying_tricep_ez","Ext Triceps EZ Tumbado","Skull crusher EZ","Triceps","Triceps","Hipertrofia","Aislamiento","Barra","Empuje","upper","anterior",3,5,2.0,1.8,0.0),
  ex("bb_floor_press_close","Press Suelo Cerrado","Press suelo agarre cerrado","Triceps","Triceps","Fuerza","Accesorio","Barra","Empuje","upper","anterior",3,6,3.0,2.8,0.2),
];
BB.forEach(e=>EX.push(["db_exp3_"+e[0],e[1],e[2],e[3],e[4],e[5],e[6],e[7],e[8],e[9],e[10],e[11],e[12],e[13],e[14],e[15]]));

// Maquinas - 50
const MQ = [
  ex("mq_chest_press_iso","Press Pecho Isolateral","Maquina press unilateral","Pectoral Medio","Pectoral Medio","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,3.0,2.2,0.0),
  ex("mq_incline_iso","Press Inclinado Isolateral","Maquina inclinada unilateral","Pectoral Superior","Pectoral Superior","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,3.0,2.2,0.0),
  ex("mq_pec_fly_iso","Pec Deck Unilateral","Aperturas maquina unilateral","Pectoral Medio","Pectoral Medio","Hipertrofia","Aislamiento","Maquina","Empuje","upper","anterior",2,3,1.6,1.2,0.0),
  ex("mq_lat_pulldown_iso","Jalon Unilateral","Jalon maquina a un brazo","Dorsal Ancho","Dorsales","Hipertrofia","Basico","Maquina","Tiron","upper","posterior",2,3,2.8,2.2,0.0),
  ex("mq_seated_row_iso","Remo Sentado Unilateral","Remo maquina unilateral","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Maquina","Tiron","upper","posterior",2,3,2.8,2.2,0.0),
  ex("mq_shoulder_press_iso","Press Hombro Unilateral","Maquina press hombro unilateral","Deltoides Anterior","Deltoides Anterior","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,2.8,2.2,0.0),
  ex("mq_lateral_raise_iso","Lateral Maquina Unilateral","Elevacion lateral maquina","Deltoides Lateral","Deltoides Lateral","Hipertrofia","Aislamiento","Maquina","Empuje","upper","anterior",1,2,1.6,1.2,0.0),
  ex("mq_rear_delt_iso","Dorsal Maquina Unilateral","Maquina deltoides posterior","Deltoides Posterior","Deltoides Posterior","Hipertrofia","Aislamiento","Maquina","Tiron","upper","posterior",1,2,1.6,1.2,0.0),
  ex("mq_shrug_iso","Encogimiento Maquina","Encogimiento en maquina","Trapecio","Trapecio","Hipertrofia","Aislamiento","Maquina","Tiron","upper","posterior",1,2,2.0,1.5,0.0),
  ex("mq_bicep_curl_iso","Curl Maquina Unilateral","Curl biceps maquina","Biceps","Biceps","Hipertrofia","Aislamiento","Maquina","Tiron","upper","anterior",1,2,1.8,1.5,0.0),
  ex("mq_tricep_ext_iso","Ext Triceps Maquina Unilateral","Extension triceps maquina","Triceps","Triceps","Hipertrofia","Aislamiento","Maquina","Empuje","upper","anterior",1,2,1.6,1.2,0.0),
  ex("mq_leg_press_45","Prensa 45 Grados","Prensa de piernas 45","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Maquina","Sentadilla","lower","anterior",3,4,3.5,2.8,0.3),
  ex("mq_leg_press_horizontal","Prensa Horizontal","Prensa piernas horizontal","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Maquina","Sentadilla","lower","anterior",3,4,3.5,2.8,0.3),
  ex("mq_leg_press_single","Prensa Unilateral","Prensa a una pierna","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Maquina","Sentadilla","lower","anterior",3,4,3.0,2.5,0.2),
  ex("mq_v_squat","V-Squat","Sentadilla en maquina V","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Maquina","Sentadilla","lower","anterior",3,4,3.5,2.8,0.5),
  ex("mq_leg_ext_single","Extension Cuadriceps Unilateral","Extension pierna unilateral","Cuadriceps","Cuadriceps","Hipertrofia","Aislamiento","Maquina","Extension","lower","anterior",2,2,2.0,1.5,0.0),
  ex("mq_leg_curl_prone","Curl Femoral Prono","Curl isquios prono maquina","Isquiosurales","Isquiosurales","Hipertrofia","Aislamiento","Maquina","Flexion","lower","posterior",2,2,2.0,1.5,0.0),
  ex("mq_leg_curl_sitting","Curl Femoral Sentado Maquina","Curl isquios sentado","Isquiosurales","Isquiosurales","Hipertrofia","Aislamiento","Maquina","Flexion","lower","posterior",2,2,2.0,1.5,0.0),
  ex("mq_calf_standing","Gemelos Maquina Pie","Gemelos maquina de pie","Gastrocnemio","Pantorrillas","Hipertrofia","Aislamiento","Maquina","Extension","lower","posterior",2,2,2.0,1.5,0.5),
  ex("mq_calf_seated","Gemelos Maquina Sentado","Gemelos maquina sentado","Soleo","Pantorrillas","Hipertrofia","Aislamiento","Maquina","Extension","lower","posterior",2,2,2.0,1.5,0.3),
  ex("mq_hip_abductor","Abductor Cadera Maquina","Maquina abduccion cadera","Gluteo Medio","Gluteos","Hipertrofia","Aislamiento","Maquina","Otro","lower","posterior",1,2,1.6,1.2,0.0),
  ex("mq_hip_adductor","Aductor Cadera Maquina","Maquina aduccion cadera","Aductores","Aductores","Hipertrofia","Aislamiento","Maquina","Otro","lower","posterior",1,2,1.6,1.2,0.0),
  ex("mq_glute_press","Maquina Gluteos","Maquina extension gluteos","Gluteos","Gluteos","Hipertrofia","Aislamiento","Maquina","Bisagra","lower","posterior",2,3,2.2,1.8,0.0),
  ex("mq_smith_bench","Press Banca Smith","Press banca en Smith","Pectoral Medio","Pectoral Medio","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,3.0,2.5,0.0),
  ex("mq_smith_incline","Press Inclinado Smith","Press inclinado Smith","Pectoral Superior","Pectoral Superior","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,3.0,2.5,0.0),
  ex("mq_smith_squat","Sentadilla Smith","Squat en Smith","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Maquina","Sentadilla","lower","anterior",3,4,3.5,2.8,0.5),
  ex("mq_smith_deadlift","Peso Muerto Smith","Deadlift en Smith","Espalda Baja","Espalda Baja","Fuerza","Basico","Maquina","Bisagra","lower","posterior",3,4,3.5,2.8,0.2),
  ex("mq_cable_row_seated","Remo Polea Sentado","Remo en polea sentado","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Polea","Tiron","upper","posterior",2,3,3.0,2.5,0.2),
  ex("mq_chest_fly_cable","Cruces Polea Baja","Cruces polea desde abajo","Pectoral Inferior","Pectoral Inferior","Hipertrofia","Aislamiento","Polea","Empuje","upper","anterior",2,3,1.8,1.5,0.0),
];
MQ.forEach(e=>EX.push(["db_exp3_"+e[0],e[1],e[2],e[3],e[4],e[5],e[6],e[7],e[8],e[9],e[10],e[11],e[12],e[13],e[14],e[15]]));

// Generate 411 more exercises programmatically
const templates = [
  { eq: "Polea", prefixes: ["cbl_"], items: [
    ["fly_high","Cruce Polea Alta","Cruces polea alta","Pectoral Superior","Pectoral Superior","Hipertrofia","Aislamiento","Empuje","upper","anterior",2,3,1.8,1.5,0.0],
    ["fly_low","Cruce Polea Baja","Cruces polea baja","Pectoral Inferior","Pectoral Inferior","Hipertrofia","Aislamiento","Empuje","upper","anterior",2,3,1.8,1.5,0.0],
    ["row_vbar","Remo Barra V Polea","Remo con barra V","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Tiron","upper","posterior",2,3,3.0,2.5,0.2],
    ["row_rope","Remo Cuerda Polea","Remo con cuerda","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Tiron","upper","posterior",2,3,2.8,2.2,0.2],
    ["row_single","Remo Unilateral Polea","Remo a un brazo polea","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Tiron","upper","posterior",2,4,2.8,2.2,0.0],
    ["lat_pulldown_v","Jalon Barra V","Jalon con barra V","Dorsal Ancho","Dorsales","Hipertrofia","Basico","Tiron","upper","posterior",2,3,3.0,2.5,0.2],
    ["lat_pulldown_ez","Jalon Barra EZ","Jalon barra curva","Dorsal Ancho","Dorsales","Hipertrofia","Basico","Tiron","upper","posterior",2,3,3.0,2.5,0.2],
    ["straight_arm_ez","Jalon Brazos Rectos EZ","Dorsal brazos rectos EZ","Dorsal Ancho","Dorsales","Hipertrofia","Aislamiento","Tiron","upper","posterior",2,3,2.2,1.8,0.0],
    ["face_pull_v","Face Pull Barra V","Tiron cara barra V","Deltoides Posterior","Deltoides Posterior","Hipertrofia","Aislamiento","Tiron","upper","posterior",2,3,1.8,1.5,0.0],
    ["lateral_single","Lateral Polea Unilateral","Elevacion lateral polea","Deltoides Lateral","Deltoides Lateral","Hipertrofia","Aislamiento","Empuje","upper","anterior",2,3,1.6,1.2,0.0],
    ["front_raise","Frontal Polea","Elevacion frontal polea","Deltoides Anterior","Deltoides Anterior","Hipertrofia","Aislamiento","Empuje","upper","anterior",2,2,1.6,1.2,0.0],
    ["shrug","Encogimiento Polea","Encogimiento en polea","Trapecio","Trapecio","Hipertrofia","Aislamiento","Tiron","upper","posterior",2,2,2.0,1.5,0.0],
    ["curl_bar","Curl Polea Barra","Curl biceps barra polea","Biceps","Biceps","Hipertrofia","Aislamiento","Tiron","upper","anterior",1,2,1.8,1.5,0.0],
    ["curl_rope","Curl Polea Cuerda","Curl biceps cuerda","Biceps","Biceps","Hipertrofia","Aislamiento","Tiron","upper","anterior",1,2,1.8,1.5,0.0],
    ["tricep_vbar","Pushdown Barra V","Pushdown triceps V","Triceps","Triceps","Hipertrofia","Aislamiento","Empuje","upper","anterior",1,2,1.8,1.5,0.0],
    ["tricep_rope","Pushdown Cuerda","Pushdown triceps cuerda","Triceps","Triceps","Hipertrofia","Aislamiento","Empuje","upper","anterior",1,2,1.8,1.5,0.0],
    ["woodchop_high","Wood Chop Alto","Wood chop polea alta","Oblicuos","Abdomen","Hipertrofia","Accesorio","Rotacion","full","full",2,4,2.0,1.5,0.0],
    ["woodchop_low","Wood Chop Bajo","Wood chop polea baja","Oblicuos","Abdomen","Hipertrofia","Accesorio","Rotacion","full","full",2,4,2.0,1.5,0.0],
    ["crunch","Crunch Polea","Crunch con polea alta","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Flexion","full","anterior",2,2,1.6,1.2,0.0],
    ["leg_curl","Curl Femoral Polea","Curl isquios polea","Isquiosurales","Isquiosurales","Hipertrofia","Aislamiento","Flexion","lower","posterior",2,3,2.0,1.5,0.0],
  ]},
  { eq: "Peso Corporal", prefixes: ["bw_"], items: [
    ["push_up_wide","Flexiones Ancho","Flexiones agarre ancho","Pectoral Medio","Pectoral Medio","Resistencia","Basico","Empuje","upper","anterior",1,3,2.8,2.2,0.1],
    ["push_up_close","Flexiones Cerrado","Flexiones agarre cerrado","Triceps","Triceps","Resistencia","Basico","Empuje","upper","anterior",1,3,2.8,2.2,0.1],
    ["push_up_sphinx","Flexiones Esfinge","Flexiones codos adelante","Triceps","Triceps","Resistencia","Basico","Empuje","upper","anterior",1,4,2.5,2.0,0.1],
    ["pike_push_up","Flexiones Pike","Flexiones pike hombros","Deltoides Anterior","Deltoides Anterior","Resistencia","Basico","Empuje","upper","anterior",1,5,2.8,2.2,0.1],
    ["decline_push_up","Flexiones Declinadas","Flexiones pies elevados","Pectoral Superior","Pectoral Superior","Resistencia","Basico","Empuje","upper","anterior",1,4,2.8,2.2,0.1],
    ["incline_push_up","Flexiones Inclinadas","Flexiones manos elevadas","Pectoral Inferior","Pectoral Inferior","Resistencia","Basico","Empuje","upper","anterior",1,2,2.5,2.0,0.1],
    ["pull_up_wide","Dominadas Ancho","Dominadas agarre ancho","Dorsal Ancho","Dorsales","Resistencia","Basico","Tiron","upper","posterior",2,5,3.2,2.5,0.2],
    ["pull_up_neutral","Dominadas Neutras","Dominadas agarre neutro","Dorsal Ancho","Dorsales","Resistencia","Basico","Tiron","upper","posterior",2,5,3.2,2.5,0.2],
    ["chin_up","Dominadas Supinas","Dominadas agarre supino","Biceps","Biceps","Resistencia","Basico","Tiron","upper","anterior",2,4,3.0,2.5,0.2],
    ["dip_bars","Fondos Barras","Fondos en barras paralelas","Triceps","Triceps","Resistencia","Basico","Empuje","upper","anterior",2,4,3.0,2.5,0.1],
    ["l_sit","L-Sit","Mantener L en barras","Recto Abdominal","Abdomen","Resistencia","Accesorio","Flexion","full","anterior",2,6,2.0,1.5,0.0],
    ["hanging_leg_raise","Elevaciones Piernas Colgado","Piernas al frente colgado","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Flexion","full","anterior",2,5,2.2,1.8,0.0],
    ["hanging_knee_raise","Elevaciones Rodillas Colgado","Rodillas al pecho colgado","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Flexion","full","anterior",2,4,2.0,1.5,0.0],
    ["plank","Plancha","Plancha frontal","Recto Abdominal","Abdomen","Resistencia","Accesorio","Otro","full","anterior",1,2,1.8,1.5,0.0],
    ["side_plank","Plancha Lateral","Plancha lateral","Oblicuos","Abdomen","Resistencia","Accesorio","Otro","full","anterior",1,3,1.6,1.2,0.0],
    ["squat_bodyweight","Sentadilla Peso Corporal","Sentadilla sin peso","Cuadriceps","Cuadriceps","Resistencia","Basico","Sentadilla","lower","anterior",1,2,2.5,2.0,0.3],
    ["lunge_forward","Zancada Frontal","Zancada hacia adelante","Cuadriceps","Cuadriceps","Resistencia","Accesorio","Sentadilla","lower","anterior",1,3,2.5,2.0,0.2],
    ["lunge_lateral","Zancada Lateral","Zancada hacia lateral","Aductores","Aductores","Resistencia","Accesorio","Otro","lower","posterior",1,3,2.2,1.8,0.0],
    ["single_leg_squat","Sentadilla Unipodal","Sentadilla a una pierna","Cuadriceps","Cuadriceps","Resistencia","Basico","Sentadilla","lower","anterior",1,6,2.8,2.2,0.2],
    ["glute_bridge","Puente Gluteos","Puente de gluteos suelo","Gluteos","Gluteos","Hipertrofia","Accesorio","Bisagra","lower","posterior",1,2,2.2,1.8,0.0],
  ]},
];
templates.forEach(t=>{
  t.items.forEach((it,i)=>{
    const id = t.prefixes[0]+it[0];
    EX.push(["db_exp3_"+id,it[1],it[2],it[3],it[4],it[5],it[6],t.eq,it[7],it[8],it[9],it[10],it[11],it[12],it[13],it[14]]);
  });
});
// Bandas - 35
const BD = [
  ["band_chest_press","Press Pecho Banda","Press pecho con banda","Pectoral Medio","Pectoral Medio","Resistencia","Basico","Banda","Empuje","upper","anterior",1,2,2.5,2.0,0.0],
  ["band_fly","Cruces Banda","Cruces pecho banda","Pectoral Medio","Pectoral Medio","Resistencia","Aislamiento","Banda","Empuje","upper","anterior",1,2,1.6,1.2,0.0],
  ["band_row","Remo Banda","Remo con banda","Dorsal Ancho","Dorsales","Resistencia","Accesorio","Banda","Tiron","upper","posterior",1,2,2.5,2.0,0.0],
  ["band_lat_pulldown","Jalon Banda","Jalon con banda anclada","Dorsal Ancho","Dorsales","Resistencia","Basico","Banda","Tiron","upper","posterior",2,3,2.5,2.0,0.0],
  ["band_shoulder_press","Press Hombro Banda","Press hombro con banda","Deltoides Anterior","Deltoides Anterior","Resistencia","Basico","Banda","Empuje","upper","anterior",1,2,2.5,2.0,0.0],
  ["band_lateral","Lateral Banda","Elevaciones laterales banda","Deltoides Lateral","Deltoides Lateral","Resistencia","Aislamiento","Banda","Empuje","upper","anterior",1,2,1.6,1.2,0.0],
  ["band_curl","Curl Banda","Curl biceps banda","Biceps","Biceps","Resistencia","Aislamiento","Banda","Tiron","upper","anterior",1,2,1.8,1.5,0.0],
  ["band_tricep_pushdown","Pushdown Banda","Pushdown triceps banda","Triceps","Triceps","Resistencia","Aislamiento","Banda","Empuje","upper","anterior",1,2,1.8,1.5,0.0],
  ["band_squat","Sentadilla Banda","Squat con banda rodillas","Cuadriceps","Cuadriceps","Resistencia","Basico","Banda","Sentadilla","lower","anterior",1,2,2.8,2.2,0.2],
  ["band_glute_bridge","Puente Banda","Puente gluteos con banda","Gluteos","Gluteos","Hipertrofia","Accesorio","Banda","Bisagra","lower","posterior",1,2,2.2,1.8,0.0],
  ["band_hip_thrust","Hip Thrust Banda","Hip thrust con banda","Gluteos","Gluteos","Hipertrofia","Accesorio","Banda","Bisagra","lower","posterior",2,3,2.5,2.0,0.0],
  ["band_rdl","RDL Banda","RDL con banda","Isquiosurales","Isquiosurales","Resistencia","Accesorio","Banda","Bisagra","lower","posterior",1,3,2.5,2.0,0.2],
  ["band_leg_curl","Curl Femoral Banda","Curl isquios banda","Isquiosurales","Isquiosurales","Resistencia","Aislamiento","Banda","Flexion","lower","posterior",2,3,1.8,1.5,0.0],
  ["band_abduction","Abduccion Banda","Abduccion cadera banda","Gluteo Medio","Gluteos","Resistencia","Aislamiento","Banda","Otro","lower","posterior",1,2,1.6,1.2,0.0],
  ["band_adduction","Aduccion Banda","Aduccion cadera banda","Aductores","Aductores","Resistencia","Aislamiento","Banda","Otro","lower","posterior",1,2,1.6,1.2,0.0],
  ["band_pallof","Pallof Press Banda","Anti-rotacion banda","Oblicuos","Abdomen","Resistencia","Accesorio","Banda","Otro","full","anterior",1,3,1.8,1.5,0.0],
  ["band_crunch","Crunch Banda","Crunch con banda","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Banda","Flexion","full","anterior",1,2,1.6,1.2,0.0],
  ["band_face_pull","Face Pull Banda","Face pull con banda","Deltoides Posterior","Deltoides Posterior","Resistencia","Aislamiento","Banda","Tiron","upper","posterior",1,2,1.8,1.5,0.0],
  ["band_upright_row","Remo Menton Banda","Remo vertical banda","Deltoides Lateral","Deltoides Lateral","Resistencia","Accesorio","Banda","Tiron","upper","anterior",1,2,2.0,1.5,0.0],
  ["band_good_morning","Good Morning Banda","Good morning banda","Isquiosurales","Isquiosurales","Resistencia","Accesorio","Banda","Bisagra","lower","posterior",1,4,2.2,1.8,0.0],
  ["band_lunge","Zancada Banda","Zancada con banda","Cuadriceps","Cuadriceps","Resistencia","Accesorio","Banda","Sentadilla","lower","anterior",1,3,2.5,2.0,0.2],
  ["band_calf_raise","Gemelos Banda","Gemelos con banda","Gastrocnemio","Pantorrillas","Resistencia","Aislamiento","Banda","Extension","lower","posterior",1,2,1.8,1.5,0.3],
  ["band_wrist_curl","Curl Muneca Banda","Flexion muneca banda","Antebrazo","Antebrazo","Resistencia","Aislamiento","Banda","Flexion","upper","anterior",1,2,1.2,1.0,0.0],
  ["band_reverse_fly","Lateral Inclinado Banda","Laterales inclinado banda","Deltoides Posterior","Deltoides Posterior","Resistencia","Aislamiento","Banda","Tiron","upper","posterior",1,3,1.6,1.2,0.0],
  ["band_chest_squeeze","Aperturas Banda","Aperturas pecho banda","Pectoral Medio","Pectoral Medio","Resistencia","Aislamiento","Banda","Empuje","upper","anterior",1,2,1.6,1.2,0.0],
  ["band_twist","Rotacion Banda","Rotacion torso banda","Oblicuos","Abdomen","Resistencia","Accesorio","Banda","Rotacion","full","full",1,2,1.6,1.2,0.0],
  ["band_superman","Superman Banda","Extension espalda banda","Espalda Baja","Espalda Baja","Resistencia","Accesorio","Banda","Extension","lower","posterior",1,3,2.0,1.5,0.0],
  ["band_monster_walk","Monster Walk","Pasos laterales banda","Gluteo Medio","Gluteos","Resistencia","Accesorio","Banda","Otro","lower","posterior",1,2,1.8,1.5,0.0],
  ["band_clam","Clam Shell Banda","Clam shell banda","Gluteo Medio","Gluteos","Resistencia","Aislamiento","Banda","Otro","lower","posterior",1,2,1.6,1.2,0.0],
  ["band_donkey_kick","Patada Gluteo Banda","Patada gluteo banda","Gluteos","Gluteos","Resistencia","Aislamiento","Banda","Bisagra","lower","posterior",1,2,1.8,1.5,0.0],
  ["band_front_raise","Frontal Banda","Elevacion frontal banda","Deltoides Anterior","Deltoides Anterior","Resistencia","Aislamiento","Banda","Empuje","upper","anterior",1,2,1.6,1.2,0.0],
  ["band_shrug","Encogimiento Banda","Encogimiento banda","Trapecio","Trapecio","Resistencia","Aislamiento","Banda","Tiron","upper","posterior",1,2,1.8,1.5,0.0],
  ["band_bicep_21","Curl 21 Banda","Curl 21 con banda","Biceps","Biceps","Hipertrofia","Aislamiento","Banda","Tiron","upper","anterior",1,3,1.8,1.5,0.0],
  ["band_overhead_ext","Ext Triceps Banda","Extension triceps banda","Triceps","Triceps","Resistencia","Aislamiento","Banda","Empuje","upper","anterior",1,2,1.6,1.2,0.0],
  ["band_single_arm_row","Remo Unilateral Banda","Remo unilateral banda","Dorsal Ancho","Dorsales","Resistencia","Accesorio","Banda","Tiron","upper","posterior",1,2,2.5,2.0,0.0],
  ["band_crossover_punch","Golpe Cruzado Banda","Golpes cruzados banda","Pectoral Medio","Pectoral Medio","Resistencia","Accesorio","Banda","Empuje","upper","anterior",1,2,2.0,1.5,0.0],
];
BD.forEach(e=>EX.push(["db_exp3_"+e[0],e[1],e[2],e[3],e[4],e[5],e[6],e[7],e[8],e[9],e[10],e[11],e[12],e[13],e[14],e[15]]));
// Kettlebells - 35
const KB = [
  ["kb_rack_carry","Marcha Rack","Caminar con KB en rack","Cuadriceps","Cuadriceps","Resistencia","Accesorio","Kettlebell","Otro","lower","anterior",2,3,2.5,2.0,0.0],
  ["kb_halo","Halo KB","Circunduccion KB cabeza","Deltoides","Hombros","Movilidad","Accesorio","Kettlebell","Otro","upper","anterior",1,3,1.5,1.2,0.0],
  ["kb_figure_8","Figure 8 KB","Figura 8 entre piernas","Core","Abdomen","Resistencia","Accesorio","Kettlebell","Rotacion","full","full",1,4,1.8,1.5,0.0],
  ["kb_renegade_row","Remo Renegado KB","Plancha remo KB","Dorsal Ancho","Dorsales","Resistencia","Accesorio","Kettlebell","Tiron","upper","posterior",2,6,2.8,2.2,0.0],
  ["kb_thruster","Thruster KB","Squat y press KB","Cuadriceps","Cuadriceps","Resistencia","Basico","Kettlebell","Empuje","full","anterior",2,5,3.0,2.5,0.2],
  ["kb_overhead_squat","Squat Overhead KB","Squat KB arriba","Cuadriceps","Cuadriceps","Estabilidad","Basico","Kettlebell","Sentadilla","full","anterior",2,7,3.0,2.5,0.2],
  ["kb_goblet_lunge","Zancada Copa KB","Zancada goblet KB","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Kettlebell","Sentadilla","lower","anterior",2,4,2.8,2.2,0.2],
  ["kb_calf_raise","Gemelos KB","Gemelos con KB","Gastrocnemio","Pantorrillas","Hipertrofia","Aislamiento","Kettlebell","Extension","lower","posterior",1,2,1.8,1.5,0.3],
  ["kb_press_single","Press KB Unilateral","Press hombro KB","Deltoides Anterior","Deltoides Anterior","Hipertrofia","Basico","Kettlebell","Empuje","upper","anterior",2,4,2.5,2.0,0.0],
  ["kb_curl","Curl KB","Curl biceps KB","Biceps","Biceps","Hipertrofia","Aislamiento","Kettlebell","Tiron","upper","anterior",1,2,1.8,1.5,0.0],
  ["kb_tricep_ext","Ext Triceps KB","Extension triceps KB","Triceps","Triceps","Hipertrofia","Aislamiento","Kettlebell","Empuje","upper","anterior",2,3,1.6,1.2,0.0],
  ["kb_bent_row","Remo Inclinado KB","Remo inclinado KB","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Kettlebell","Tiron","upper","posterior",2,4,2.8,2.2,0.0],
  ["kb_front_raise","Frontal KB","Elevacion frontal KB","Deltoides Anterior","Deltoides Anterior","Hipertrofia","Aislamiento","Kettlebell","Empuje","upper","anterior",1,2,1.6,1.2,0.0],
  ["kb_lateral_raise","Lateral KB","Elevacion lateral KB","Deltoides Lateral","Deltoides Lateral","Hipertrofia","Aislamiento","Kettlebell","Empuje","upper","anterior",1,2,1.6,1.2,0.0],
  ["kb_shrug","Encogimiento KB","Encogimiento con KB","Trapecio","Trapecio","Hipertrofia","Aislamiento","Kettlebell","Tiron","upper","posterior",1,2,2.0,1.5,0.0],
  ["kb_rdl","RDL KB","RDL con KB","Isquiosurales","Isquiosurales","Hipertrofia","Accesorio","Kettlebell","Bisagra","lower","posterior",2,4,2.8,2.2,0.2],
  ["kb_sumo_squat","Sentadilla Sumo KB","Sumo squat KB","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Kettlebell","Sentadilla","lower","anterior",2,4,2.8,2.2,0.2],
  ["kb_glute_bridge","Puente KB","Puente gluteos KB","Gluteos","Gluteos","Hipertrofia","Accesorio","Kettlebell","Bisagra","lower","posterior",2,3,2.2,1.8,0.0],
  ["kb_high_pull","High Pull KB","Tiron alto KB","Trapecio","Trapecio","Hipertrofia","Accesorio","Kettlebell","Tiron","upper","anterior",2,4,2.2,1.8,0.0],
  ["kb_around_world","Around World KB","KB alrededor cuerpo","Deltoides","Hombros","Resistencia","Accesorio","Kettlebell","Otro","upper","anterior",1,3,1.5,1.2,0.0],
  ["kb_deadlift_single","Peso Muerto KB Unilateral","Deadlift KB una mano","Espalda Baja","Espalda Baja","Resistencia","Accesorio","Kettlebell","Bisagra","lower","posterior",2,4,2.5,2.0,0.2],
  ["kb_goblet_hold","Sostener Copa KB","Mantener goblet isometrico","Core","Abdomen","Resistencia","Accesorio","Kettlebell","Otro","full","anterior",1,2,1.5,1.2,0.0],
  ["kb_swing_single","Swing KB Unilateral","Swing a una mano","Gluteos","Gluteos","Resistencia","Basico","Kettlebell","Bisagra","lower","posterior",1,4,2.8,2.2,0.2],
  ["kb_snatch_single","Snatch KB Unilateral","Snatch a una mano","Gluteos","Gluteos","Resistencia","Basico","Kettlebell","Bisagra","full","posterior",2,6,3.0,2.5,0.2],
  ["kb_clean_single","Clean KB Unilateral","Clean a una mano","Gluteos","Gluteos","Resistencia","Basico","Kettlebell","Bisagra","full","posterior",2,5,2.8,2.2,0.2],
  ["kb_tgu_halfloaded","Get Up Medio","Turkish get up parcial","Core","Abdomen","Estabilidad","Accesorio","Kettlebell","Otro","full","full",2,6,2.0,1.5,0.0],
  ["kb_farmers_walk","Marcha Granjero KB","Marcha con KB","Trapecio","Trapecio","Resistencia","Accesorio","Kettlebell","Otro","full","posterior",1,2,2.2,1.8,0.0],
  ["kb_rack_squat_single","Squat Rack KB Unilateral","Squat rack una KB","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Kettlebell","Sentadilla","lower","anterior",2,4,2.8,2.2,0.2],
  ["kb_around_body","Alrededor Cuerpo KB","Pasar KB alrededor cadera","Core","Abdomen","Resistencia","Accesorio","Kettlebell","Rotacion","full","full",1,2,1.5,1.2,0.0],
  ["kb_bottoms_up_carry","Marcha Bottoms Up","Caminar KB invertida","Antebrazo","Antebrazo","Estabilidad","Accesorio","Kettlebell","Otro","upper","anterior",1,4,1.8,1.5,0.0],
  ["kb_pullover","Pullover KB","Pullover con KB","Pectoral Medio","Pectoral Medio","Hipertrofia","Aislamiento","Kettlebell","Tiron","upper","anterior",2,3,1.8,1.5,0.0],
  ["kb_floor_press_single","Press Suelo KB Unilateral","Press suelo KB","Pectoral Medio","Pectoral Medio","Hipertrofia","Accesorio","Kettlebell","Empuje","upper","anterior",2,3,2.5,2.0,0.0],
  ["kb_upright_row","Remo Menton KB","Remo vertical KB","Deltoides Lateral","Deltoides Lateral","Hipertrofia","Accesorio","Kettlebell","Tiron","upper","anterior",1,3,2.2,1.8,0.0],
  ["kb_leg_raise","Elevacion Piernas KB","Piernas con KB entre pies","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Kettlebell","Flexion","full","anterior",2,4,2.0,1.5,0.0],
  ["kb_windmill_single","Molino KB Unilateral","Windmill a un lado","Oblicuos","Abdomen","Movilidad","Accesorio","Kettlebell","Rotacion","full","full",2,6,1.8,1.5,0.0],
  ["kb_double_farmers","Marcha Doble KB","Marcha dos KB","Trapecio","Trapecio","Resistencia","Accesorio","Kettlebell","Otro","full","posterior",2,2,2.5,2.0,0.0],
];
KB.forEach(e=>EX.push(["db_exp3_"+e[0],e[1],e[2],e[3],e[4],e[5],e[6],e[7],e[8],e[9],e[10],e[11],e[12],e[13],e[14],e[15]]));

// Abdominales y Core - 70
const AB = [
  ["ab_crunch_basic","Crunch Basico","Crunch clasico suelo","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,1,1.6,1.2,0.0],
  ["ab_crunch_bicycle","Crunch Bicicleta","Crunch pedaleo","Oblicuos","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,2,1.8,1.5,0.0],
  ["ab_crunch_reverse","Crunch Inverso","Crunch piernas al pecho","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_crunch_twist","Crunch Giro","Crunch con rotacion","Oblicuos","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_vertical_leg","Piernas Verticales","Piernas arriba suelo","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,3,1.8,1.5,0.0],
  ["ab_v_up","V-Up","V-up completo","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,4,2.0,1.5,0.0],
  ["ab_mountain_climber","Escalador","Mountain climber","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,3,2.0,1.5,0.1],
  ["ab_dead_bug","Dead Bug","Dead bug controlado","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,3,1.6,1.2,0.0],
  ["ab_bird_dog","Bird Dog","Bird dog alterno","Espalda Baja","Espalda Baja","Resistencia","Accesorio","Peso Corporal","Otro","full","posterior",1,2,1.6,1.2,0.0],
  ["ab_superman","Superman","Extension espalda suelo","Espalda Baja","Espalda Baja","Resistencia","Accesorio","Peso Corporal","Extension","full","posterior",1,2,1.8,1.5,0.0],
  ["ab_plank_alt","Plancha Alterna","Plancha tocando hombros","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,3,1.8,1.5,0.0],
  ["ab_plank_reach","Plancha Alcance","Plancha con alcance","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,4,1.8,1.5,0.0],
  ["ab_side_plank_dip","Plancha Lateral Dip","Plancha lateral con dip","Oblicuos","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,4,1.8,1.5,0.0],
  ["ab_side_plank_raise","Plancha Lateral Pierna","Plancha lateral pierna arriba","Oblicuos","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,4,1.8,1.5,0.0],
  ["ab_rollout_wheel","Rollout Rueda","Ab rollout con rueda","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,5,2.2,1.8,0.0],
  ["ab_rollout_ring","Rollout Anillas","Rollout con anillas","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",2,6,2.2,1.8,0.0],
  ["ab_leg_drop","Caida Piernas","Bajar piernas controlado","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,3,1.8,1.5,0.0],
  ["ab_dragon_flag","Dragon Flag","Dragon flag progresion","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",2,8,2.5,2.0,0.0],
  ["ab_hollow_body","Hollow Body","Hollow body hold","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,4,1.8,1.5,0.0],
  ["ab_arch_hold","Arch Hold","Arch hold isometrico","Espalda Baja","Espalda Baja","Resistencia","Accesorio","Peso Corporal","Extension","full","posterior",1,3,1.6,1.2,0.0],
  ["ab_russian_twist","Giro Ruso","Russian twist","Oblicuos","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Rotacion","full","full",1,3,1.8,1.5,0.0],
  ["ab_woodchop_body","Wood Chop Corporal","Wood chop sin equipo","Oblicuos","Abdomen","Resistencia","Accesorio","Peso Corporal","Rotacion","full","full",1,3,1.6,1.2,0.0],
  ["ab_crossover_crunch","Crunch Cruzado","Crunch codo a rodilla","Oblicuos","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_scissor_kick","Tijeras","Tijeras piernas","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_flutter_kick","Flutter Kick","Flutter kick","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_toe_touch","Toque Puntas","Toque puntas acostado","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_plank_shoulder_tap","Plancha Toques","Plancha tocar hombros","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,4,2.0,1.5,0.0],
  ["ab_reverse_crunch_bench","Crunch Inverso Banco","Crunch inverso en banco","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",2,3,1.8,1.5,0.0],
  ["ab_cable_crunch_kneel","Crunch Polea Rodillas","Crunch polea arrodillado","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Polea","Flexion","full","anterior",2,3,2.0,1.5,0.0],
  ["ab_cable_crunch_stand","Crunch Polea Pie","Crunch polea de pie","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Polea","Flexion","full","anterior",2,4,2.0,1.5,0.0],
  ["ab_pallof_hold","Pallof Hold","Anti-rotacion isometrica","Oblicuos","Abdomen","Resistencia","Accesorio","Polea","Otro","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_cable_rotation","Rotacion Polea","Rotacion torso polea","Oblicuos","Abdomen","Hipertrofia","Accesorio","Polea","Rotacion","full","full",2,3,1.8,1.5,0.0],
  ["ab_hanging_oblique","Obliquos Colgado","Obliquos en barra","Oblicuos","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",2,5,2.2,1.8,0.0],
  ["ab_stability_ball_crunch","Crunch Fitball","Crunch en fitball","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",2,3,1.8,1.5,0.0],
  ["ab_stability_ball_rollout","Rollout Fitball","Rollout en fitball","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",2,4,2.0,1.5,0.0],
  ["ab_ab_wheel_standing","Rueda Abdominal Pie","Rollout de pie","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,6,2.2,1.8,0.0],
  ["ab_sit_up","Sit Up","Sit up clasico","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_v_sit_up","V Sit Up","Sit up en V","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,3,1.8,1.5,0.0],
  ["ab_twist_sit_up","Sit Up Giro","Sit up con giro","Oblicuos","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_candlestick","Candelabro","Candelabro piernas","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,4,1.8,1.5,0.0],
  ["ab_heel_tap","Toque Talones","Toque talones acostado","Oblicuos","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_dead_bug_single","Dead Bug Unilateral","Dead bug una pierna","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,3,1.6,1.2,0.0],
  ["ab_hip_dip","Hip Dip","Hip dip lateral","Oblicuos","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,3,1.8,1.5,0.0],
  ["ab_plank_up_down","Plancha Subir Bajar","Plancha antebrazo a mano","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,4,2.0,1.5,0.0],
  ["ab_body_saw","Body Saw","Body saw en antebrazos","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,5,2.0,1.5,0.0],
  ["ab_stir_the_pot","Stir the Pot","Circular en fitball","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",2,5,1.8,1.5,0.0],
  ["ab_roll_up","Roll Up","Roll up pilates","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,3,1.8,1.5,0.0],
  ["ab_double_leg_stretch","Doble Pierna Estirar","Pilates doble pierna","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,3,1.6,1.2,0.0],
  ["ab_single_leg_stretch","Pierna Simple Estirar","Pilates pierna simple","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",1,3,1.6,1.2,0.0],
  ["ab_hundred","Cien","Ejercicio los cien","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,3,1.8,1.5,0.0],
  ["ab_bear_crawl","Marcha Oso","Bear crawl","Core","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,3,2.0,1.5,0.0],
  ["ab_quadruped_reach","Cuadrupedia Alcance","Alcance cuadrupedia","Core","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,3,1.6,1.2,0.0],
  ["ab_supine_march","Marcha Supino","Marcha acostado","Recto Abdominal","Abdomen","Resistencia","Accesorio","Peso Corporal","Otro","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_crunch_weighted","Crunch Ponderado","Crunch con disco","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Mancuerna","Flexion","full","anterior",2,2,1.8,1.5,0.0],
  ["ab_russian_twist_weighted","Giro Ruso Ponderado","Russian twist con peso","Oblicuos","Abdomen","Hipertrofia","Aislamiento","Mancuerna","Rotacion","full","full",1,3,1.8,1.5,0.0],
  ["ab_side_bend","Flexion Lateral","Flexion lateral con peso","Oblicuos","Abdomen","Hipertrofia","Aislamiento","Mancuerna","Otro","full","anterior",1,2,1.6,1.2,0.0],
  ["ab_landmine_twist","Giro Landmine","Rotacion landmine","Oblicuos","Abdomen","Hipertrofia","Accesorio","Barra","Rotacion","full","full",3,4,2.0,1.5,0.0],
  ["ab_landmine_press","Press Landmine","Press landmine rotacion","Core","Abdomen","Hipertrofia","Accesorio","Barra","Empuje","full","anterior",3,4,2.2,1.8,0.0],
  ["ab_back_extension","Extension Espalda","Extension espalda banco","Espalda Baja","Espalda Baja","Hipertrofia","Aislamiento","Maquina","Extension","full","posterior",2,3,2.0,1.5,0.0],
  ["ab_back_extension_hyper","Hiperextension","Hiperextension romana","Espalda Baja","Espalda Baja","Hipertrofia","Aislamiento","Maquina","Extension","full","posterior",2,3,2.2,1.8,0.0],
  ["ab_ghd_sit_up","GHD Sit Up","Sit up GHD","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Maquina","Flexion","full","anterior",3,5,2.5,2.0,0.0],
  ["ab_ghd_back_ext","GHD Extension","Extension GHD","Espalda Baja","Espalda Baja","Hipertrofia","Aislamiento","Maquina","Extension","full","posterior",3,4,2.2,1.8,0.0],
  ["ab_decline_sit_up","Sit Up Declive","Sit up banco declive","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",2,3,2.0,1.5,0.0],
  ["ab_incline_leg_raise","Elevacion Piernas Inclinado","Piernas banco inclinado","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",2,3,2.0,1.5,0.0],
  ["ab_captain_chair","Silla Capitan","Elevaciones silla capitan","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Maquina","Flexion","full","anterior",1,2,2.0,1.5,0.0],
  ["ab_oblique_crunch_bench","Crunch Obliquos Banco","Crunch obliquos banco","Oblicuos","Abdomen","Hipertrofia","Aislamiento","Peso Corporal","Flexion","full","anterior",2,3,1.8,1.5,0.0],
];
AB.forEach(e=>EX.push(["db_exp3_"+e[0],e[1],e[2],e[3],e[4],e[5],e[6],e[7],e[8],e[9],e[10],e[11],e[12],e[13],e[14],e[15]]));

// Piernas variantes - 80
const LG = [
  ["lg_bulgarian_split","Zancada Bulgaria","Zancada pie atras elevado","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Mancuerna","Sentadilla","lower","anterior",3,6,2.8,2.2,0.2],
  ["lg_bulgarian_barbell","Zancada Bulgaria Barra","Bulgarian con barra","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Barra","Sentadilla","lower","anterior",4,6,3.0,2.5,0.2],
  ["lg_front_rack_lunge","Zancada Rack Frontal","Zancada barra frontal","Cuadriceps","Cuadriceps","Fuerza","Accesorio","Barra","Sentadilla","lower","anterior",4,6,3.0,2.5,0.2],
  ["lg_walking_lunge_db","Zancada Caminando Mancuerna","Zancada caminando DB","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Mancuerna","Sentadilla","lower","anterior",2,4,2.8,2.2,0.2],
  ["lg_walking_lunge_bb","Zancada Caminando Barra","Zancada caminando barra","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Barra","Sentadilla","lower","anterior",4,5,3.0,2.5,0.2],
  ["lg_step_up","Subir Escalon","Step up con peso","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Mancuerna","Sentadilla","lower","anterior",2,3,2.5,2.0,0.2],
  ["lg_step_up_bb","Subir Escalon Barra","Step up barra","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Barra","Sentadilla","lower","anterior",4,4,2.8,2.2,0.2],
  ["lg_pistol_squat","Pistol Squat","Sentadilla unipodal","Cuadriceps","Cuadriceps","Resistencia","Basico","Peso Corporal","Sentadilla","lower","anterior",1,8,2.8,2.2,0.2],
  ["lg_shrimp_squat","Shrimp Squat","Squat camarÃƒÂ³n","Cuadriceps","Cuadriceps","Resistencia","Basico","Peso Corporal","Sentadilla","lower","anterior",1,7,2.5,2.0,0.2],
  ["lg_cossack_squat","Sentadilla Cosaco","Squat cosaco","Aductores","Aductores","Resistencia","Accesorio","Peso Corporal","Sentadilla","lower","posterior",1,5,2.2,1.8,0.0],
  ["lg_slider_leg_curl","Curl Femoral Slider","Curl isquios con slider","Isquiosurales","Isquiosurales","Resistencia","Aislamiento","Peso Corporal","Flexion","lower","posterior",1,4,1.8,1.5,0.0],
  ["lg_nordic_curl","Curl Nordico","Curl nordico excÃƒÂ©ntrico","Isquiosurales","Isquiosurales","Hipertrofia","Aislamiento","Peso Corporal","Flexion","lower","posterior",1,8,2.5,2.0,0.0],
  ["lg_good_morning","Good Morning","Good morning barra","Isquiosurales","Isquiosurales","Hipertrofia","Accesorio","Barra","Bisagra","lower","posterior",3,5,2.5,2.0,0.2],
  ["lg_good_morning_db","Good Morning Mancuerna","Good morning DB","Isquiosurales","Isquiosurales","Hipertrofia","Accesorio","Mancuerna","Bisagra","lower","posterior",2,4,2.2,1.8,0.0],
  ["lg_sldl","Peso Muerto Piernas RÃƒÂ­gidas","SDL barra","Isquiosurales","Isquiosurales","Hipertrofia","Basico","Barra","Bisagra","lower","posterior",3,5,3.0,2.5,0.2],
  ["lg_sldl_db","SDL Mancuerna","Peso muerto piernas rigidas DB","Isquiosurales","Isquiosurales","Hipertrofia","Basico","Mancuerna","Bisagra","lower","posterior",2,4,2.8,2.2,0.2],
  ["lg_cable_leg_curl","Curl Femoral Polea","Curl isquios polea","Isquiosurales","Isquiosurales","Hipertrofia","Aislamiento","Polea","Flexion","lower","posterior",2,3,2.0,1.5,0.0],
  ["lg_cable_leg_ext","Extension Cuadriceps Polea","Extension cuadriceps polea","Cuadriceps","Cuadriceps","Hipertrofia","Aislamiento","Polea","Extension","lower","anterior",2,3,2.0,1.5,0.0],
  ["lg_calf_raise_leg_press","Gemelos Prensa","Gemelos en prensa","Gastrocnemio","Pantorrillas","Hipertrofia","Aislamiento","Maquina","Extension","lower","posterior",2,2,2.0,1.5,0.3],
  ["lg_calf_raise_donkey","Gemelos Burro","Gemelos burro","Gastrocnemio","Pantorrillas","Hipertrofia","Aislamiento","Peso Corporal","Extension","lower","posterior",2,3,1.8,1.5,0.3],
  ["lg_calf_raise_single_leg","Gemelos Unipodal","Gemelos a una pierna","Gastrocnemio","Pantorrillas","Hipertrofia","Aislamiento","Peso Corporal","Extension","lower","posterior",1,2,1.6,1.2,0.3],
  ["lg_calf_raise_incline","Gemelos Inclinado","Gemelos en pendiente","Gastrocnemio","Pantorrillas","Hipertrofia","Aislamiento","Peso Corporal","Extension","lower","posterior",1,2,1.8,1.5,0.5],
  ["lg_hip_thrust_bb","Hip Thrust Barra","Hip thrust barra","Gluteos","Gluteos","Hipertrofia","Basico","Barra","Bisagra","lower","posterior",4,5,3.2,2.5,0.2],
  ["lg_hip_thrust_db","Hip Thrust Mancuerna","Hip thrust mancuerna","Gluteos","Gluteos","Hipertrofia","Basico","Mancuerna","Bisagra","lower","posterior",3,4,2.8,2.2,0.0],
  ["lg_hip_thrust_single","Hip Thrust Unilateral","Hip thrust una pierna","Gluteos","Gluteos","Hipertrofia","Accesorio","Peso Corporal","Bisagra","lower","posterior",2,5,2.5,2.0,0.0],
  ["lg_glute_bridge_single","Puente Unilateral","Puente gluteos una pierna","Gluteos","Gluteos","Hipertrofia","Accesorio","Peso Corporal","Bisagra","lower","posterior",1,3,2.2,1.8,0.0],
  ["lg_cable_kickback","Patada Polea","Patada gluteo polea","Gluteos","Gluteos","Hipertrofia","Aislamiento","Polea","Bisagra","lower","posterior",2,3,2.0,1.5,0.0],
  ["lg_curtsy_lunge","Zancada Reverencia","Zancada curtsy","Gluteos","Gluteos","Hipertrofia","Accesorio","Mancuerna","Sentadilla","lower","posterior",2,4,2.5,2.0,0.0],
  ["lg_lateral_lunge","Zancada Lateral","Zancada lateral","Aductores","Aductores","Hipertrofia","Accesorio","Mancuerna","Otro","lower","posterior",2,4,2.5,2.0,0.0],
  ["lg_skater_squat","Skater Squat","Squat patinador","Cuadriceps","Cuadriceps","Resistencia","Basico","Peso Corporal","Sentadilla","lower","anterior",1,7,2.5,2.0,0.2],
  ["lg_box_squat","Sentadilla Caja","Squat a caja","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Barra","Sentadilla","lower","anterior",4,5,3.5,2.8,0.5],
  ["lg_pause_squat","Sentadilla Pausa","Squat con pausa","Cuadriceps","Cuadriceps","Fuerza","Basico","Barra","Sentadilla","lower","anterior",4,5,3.5,2.8,0.3],
  ["lg_pin_squat","Sentadilla Pin","Squat desde pins","Cuadriceps","Cuadriceps","Fuerza","Basico","Barra","Sentadilla","lower","anterior",4,5,3.5,2.8,0.2],
  ["lg_jump_squat","Salto Sentadilla","Jump squat","Cuadriceps","Cuadriceps","Resistencia","Accesorio","Peso Corporal","Sentadilla","lower","anterior",1,4,2.5,2.0,0.5],
  ["lg_sumo_squat_bb","Sentadilla Sumo Barra","Sumo squat barra","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Barra","Sentadilla","lower","anterior",4,5,3.5,2.8,0.5],
  ["lg_jefferson_squat","Jefferson Squat","Squat Jefferson","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Barra","Sentadilla","lower","anterior",4,6,3.2,2.5,0.2],
  ["lg_sissy_squat_hold","Sissy Squat Pausa","Sissy squat con pausa","Cuadriceps","Cuadriceps","Hipertrofia","Aislamiento","Peso Corporal","Extension","lower","anterior",1,6,2.2,1.8,0.0],
  ["lg_terminal_knee_ext","Extension Rodilla Terminal","Extension rodilla sentado","Cuadriceps","Cuadriceps","Rehabilitacion","Aislamiento","Peso Corporal","Extension","lower","anterior",1,1,1.2,1.0,0.0],
  ["lg_leg_press_wide","Prensa Ancha","Prensa piernas ancha","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Maquina","Sentadilla","lower","anterior",3,3,3.5,2.8,0.3],
  ["lg_leg_press_narrow","Prensa Cerrada","Prensa piernas cerrada","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Maquina","Sentadilla","lower","anterior",3,3,3.5,2.8,0.3],
  ["lg_leg_press_single_foot","Prensa Unipodal","Prensa un pie","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Maquina","Sentadilla","lower","anterior",3,4,2.8,2.2,0.2],
  ["lg_glute_ham_raise","Glute Ham Raise","GHR en maquina","Isquiosurales","Isquiosurales","Hipertrofia","Aislamiento","Maquina","Flexion","lower","posterior",3,6,2.8,2.2,0.0],
  ["lg_reverse_hyper","Hiperextension Inversa","Reverse hyper","Gluteos","Gluteos","Hipertrofia","Aislamiento","Maquina","Bisagra","lower","posterior",2,4,2.5,2.0,0.0],
  ["lg_hip_abduction_standing","Abduccion Pie","Abduccion de pie","Gluteo Medio","Gluteos","Hipertrofia","Aislamiento","Maquina","Otro","lower","posterior",1,2,1.6,1.2,0.0],
  ["lg_hip_adduction_standing","Aduccion Pie","Aduccion de pie","Aductores","Aductores","Hipertrofia","Aislamiento","Maquina","Otro","lower","posterior",1,2,1.6,1.2,0.0],
  ["lg_squat_narrow_bb","Sentadilla Cerrada Barra","Squat agarre cerrado","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Barra","Sentadilla","lower","anterior",4,5,3.5,2.8,0.5],
  ["lg_front_squat_pause","Front Squat Pausa","Front squat pausa abajo","Cuadriceps","Cuadriceps","Fuerza","Basico","Barra","Sentadilla","lower","anterior",4,6,3.5,3.0,0.5],
  ["lg_deadlift_pause","Peso Muerto Pausa","Deadlift pausa rodilla","Espalda Baja","Espalda Baja","Fuerza","Basico","Barra","Bisagra","lower","posterior",4,5,3.5,3.0,0.2],
  ["lg_rdl_pause","RDL Pausa","RDL pausa estiramiento","Isquiosurales","Isquiosurales","Hipertrofia","Basico","Barra","Bisagra","lower","posterior",3,5,3.0,2.5,0.3],
  ["lg_squat_jump_bb","Squat Jump Barra","Jump squat con barra","Cuadriceps","Cuadriceps","Resistencia","Accesorio","Barra","Sentadilla","lower","anterior",4,5,2.8,2.2,0.5],
  ["lg_deficit_rdl","RDL Deficit","RDL desde elevacion","Isquiosurales","Isquiosurales","Hipertrofia","Accesorio","Mancuerna","Bisagra","lower","posterior",2,5,2.8,2.2,0.3],
  ["lg_single_leg_rdl","RDL Unipodal","RDL una pierna","Isquiosurales","Isquiosurales","Hipertrofia","Accesorio","Mancuerna","Bisagra","lower","posterior",2,6,2.5,2.0,0.2],
  ["lg_copenhagen_plank","Plancha Copenhagen","Plancha aduccion","Aductores","Aductores","Resistencia","Accesorio","Peso Corporal","Otro","lower","posterior",2,6,1.8,1.5,0.0],
  ["lg_leg_extension_hold","Extension Cuadriceps Pausa","Extension con pausa","Cuadriceps","Cuadriceps","Hipertrofia","Aislamiento","Maquina","Extension","lower","anterior",2,2,2.0,1.5,0.0],
  ["lg_leg_curl_hold","Curl Femoral Pausa","Curl isquios pausa","Isquiosurales","Isquiosurales","Hipertrofia","Aislamiento","Maquina","Flexion","lower","posterior",2,2,2.0,1.5,0.0],
  ["lg_wall_sit","Sentada Pared","Isometrico pared","Cuadriceps","Cuadriceps","Resistencia","Accesorio","Peso Corporal","Sentadilla","lower","anterior",1,2,2.0,1.5,0.0],
  ["lg_hip_hinge_hold","Bisagra Cadera Pausa","Hip hinge isometrico","Isquiosurales","Isquiosurales","Resistencia","Accesorio","Barra","Bisagra","lower","posterior",3,4,2.5,2.0,0.0],
  ["lg_sumo_deadlift_high_handle","Sumo Deadlift Alto","Sumo deadlift handles altos","Espalda Baja","Espalda Baja","Fuerza","Basico","Maquina","Bisagra","lower","posterior",3,4,3.5,2.8,0.2],
  ["lg_trap_bar_deadlift","Peso Muerto Trap Bar","Deadlift hex bar","Espalda Baja","Espalda Baja","Fuerza","Basico","Barra","Bisagra","lower","posterior",3,4,3.8,3.0,0.2],
  ["lg_trap_bar_squat","Squat Trap Bar","Squat hex bar","Cuadriceps","Cuadriceps","Fuerza","Basico","Barra","Sentadilla","lower","anterior",3,4,3.5,2.8,0.5],
  ["lg_goblet_squat_pause","Goblet Pausa","Goblet squat pausa","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Mancuerna","Sentadilla","lower","anterior",2,4,3.0,2.5,0.3],
  ["lg_box_step_down","Bajar Caja","Step down controlado","Cuadriceps","Cuadriceps","Resistencia","Accesorio","Peso Corporal","Sentadilla","lower","anterior",1,3,2.0,1.5,0.0],
  ["lg_sliding_lunge","Zancada Deslizante","Lunge con slider","Cuadriceps","Cuadriceps","Resistencia","Accesorio","Peso Corporal","Sentadilla","lower","anterior",1,4,2.2,1.8,0.0],
  ["lg_leg_press_calf","Gemelos Prensadora","Gemelos en prensadora","Soleo","Pantorrillas","Hipertrofia","Aislamiento","Maquina","Extension","lower","posterior",2,2,2.0,1.5,0.3],
  ["lg_seated_calf_single","Gemelos Sentado Unilateral","Gemelos sentado una pierna","Soleo","Pantorrillas","Hipertrofia","Aislamiento","Maquina","Extension","lower","posterior",2,2,1.8,1.5,0.3],
  ["lg_tibia_raise","Elevacion Tibial","Elevacion tibia anterior","Tibial Anterior","Pantorrillas","Resistencia","Aislamiento","Peso Corporal","Extension","lower","anterior",1,2,1.2,1.0,0.0],
];
LG.forEach(e=>EX.push(["db_exp3_"+e[0],e[1],e[2],e[3],e[4],e[5],e[6],e[7],e[8],e[9],e[10],e[11],e[12],e[13],e[14],e[15]]));

// Trapecio, antebrazo y variantes extra - 170
const TR = [
  ["tr_shrug_db","Encogimiento Mancuerna","Encogimiento con mancuernas","Trapecio","Trapecio","Hipertrofia","Aislamiento","Mancuerna","Tiron","upper","posterior",2,2,2.0,1.5,0.0],
  ["tr_shrug_bb_behind","Encogimiento Barra Atras","Encogimiento barra detras","Trapecio","Trapecio","Hipertrofia","Aislamiento","Barra","Tiron","upper","posterior",3,3,2.0,1.5,0.0],
  ["tr_shrug_rotate_db","Encogimiento Rotatorio","Encogimiento con rotacion","Trapecio","Trapecio","Hipertrofia","Aislamiento","Mancuerna","Tiron","upper","posterior",2,3,2.0,1.5,0.0],
  ["tr_shrug_hold","Encogimiento Pausa","Encogimiento con pausa","Trapecio","Trapecio","Hipertrofia","Aislamiento","Barra","Tiron","upper","posterior",2,3,2.0,1.5,0.0],
  ["tr_shrug_cable","Encogimiento Polea","Encogimiento polea","Trapecio","Trapecio","Hipertrofia","Aislamiento","Polea","Tiron","upper","posterior",2,2,2.0,1.5,0.0],
  ["tr_farmers_walk","Marcha Granjero","Marcha con mancuernas","Trapecio","Trapecio","Resistencia","Accesorio","Mancuerna","Otro","full","posterior",1,2,2.5,2.0,0.0],
  ["tr_suitcase_carry","Marcha Maletin","Marcha unilateral","Trapecio","Trapecio","Resistencia","Accesorio","Mancuerna","Otro","full","posterior",1,2,2.2,1.8,0.0],
  ["tr_trap_bar_shrug","Encogimiento Trap Bar","Encogimiento hex bar","Trapecio","Trapecio","Hipertrofia","Aislamiento","Barra","Tiron","upper","posterior",3,3,2.2,1.8,0.0],
  ["tr_rack_pull_shrug","Rack Pull Encogimiento","Rack pull con encogimiento","Trapecio","Trapecio","Fuerza","Accesorio","Barra","Tiron","upper","posterior",3,4,3.0,2.5,0.0],
  ["tr_face_pull_high","Face Pull Alto","Face pull angulo alto","Trapecio","Trapecio","Hipertrofia","Aislamiento","Polea","Tiron","upper","posterior",2,3,1.8,1.5,0.0],
  ["af_wrist_curl_db","Curl Muneca Mancuerna","Flexion muneca mancuerna","Antebrazo","Antebrazo","Hipertrofia","Aislamiento","Mancuerna","Flexion","upper","anterior",1,2,1.2,1.0,0.0],
  ["af_wrist_curl_ez","Curl Muneca EZ","Flexion muneca barra EZ","Antebrazo","Antebrazo","Hipertrofia","Aislamiento","Barra","Flexion","upper","anterior",1,2,1.2,1.0,0.0],
  ["af_reverse_wrist_db","Curl Inverso Muneca DB","Extension muneca mancuerna","Antebrazo","Antebrazo","Hipertrofia","Aislamiento","Mancuerna","Extension","upper","anterior",1,2,1.2,1.0,0.0],
  ["af_reverse_wrist_ez","Curl Inverso Muneca EZ","Extension muneca EZ","Antebrazo","Antebrazo","Hipertrofia","Aislamiento","Barra","Extension","upper","anterior",1,2,1.2,1.0,0.0],
  ["af_wrist_roller","Rollo Muneca","Rollo de munecas","Antebrazo","Antebrazo","Hipertrofia","Aislamiento","Peso Corporal","Flexion","upper","anterior",1,2,1.2,1.0,0.0],
  ["af_plate_pinch","Pinza Disco","Sostener disco con dedos","Antebrazo","Antebrazo","Hipertrofia","Aislamiento","Peso Corporal","Otro","upper","anterior",1,1,1.0,1.0,0.0],
  ["af_dead_hang","Colgar Muerto","Colgar en barra","Antebrazo","Antebrazo","Resistencia","Accesorio","Peso Corporal","Tiron","upper","anterior",1,2,1.5,1.2,0.0],
  ["af_towel_hang","Colgar Toalla","Colgar con toalla","Antebrazo","Antebrazo","Resistencia","Accesorio","Peso Corporal","Tiron","upper","anterior",1,4,1.8,1.5,0.0],
  ["af_reverse_curl_ez","Curl Inverso EZ","Curl inverso barra EZ","Antebrazo","Antebrazo","Hipertrofia","Aislamiento","Barra","Tiron","upper","anterior",2,3,1.6,1.2,0.0],
  ["af_hammer_curl_db","Curl Martillo Mancuerna","Curl martillo DB","Biceps","Biceps","Hipertrofia","Aislamiento","Mancuerna","Tiron","upper","anterior",2,2,1.8,1.5,0.0],
  ["af_radial_deviation","Desviacion Radial","Desviacion radial muneca","Antebrazo","Antebrazo","Hipertrofia","Aislamiento","Mancuerna","Otro","upper","anterior",1,2,1.0,1.0,0.0],
  ["af_ulnar_deviation","Desviacion Cubital","Desviacion cubital","Antebrazo","Antebrazo","Hipertrofia","Aislamiento","Mancuerna","Otro","upper","anterior",1,2,1.0,1.0,0.0],
];
TR.forEach(e=>EX.push(["db_exp3_"+e[0],e[1],e[2],e[3],e[4],e[5],e[6],e[7],e[8],e[9],e[10],e[11],e[12],e[13],e[14],e[15]]));

// Mas variantes barra - 40
const BB2 = [
  ["bb2_bench_close","Press Banca Cerrado","Banca agarre cerrado","Triceps","Triceps","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,4,3.0,2.5,0.0],
  ["bb2_incline_close","Press Inclinado Cerrado","Inclinado agarre cerrado","Pectoral Superior","Pectoral Superior","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,4,3.0,2.5,0.0],
  ["bb2_ohp_behind","Press Militar Atras","Press por detras nuca","Deltoides Lateral","Deltoides Lateral","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,5,3.2,2.5,0.2],
  ["bb2_ohp_push","Press Militar Frente","Press militar frente","Deltoides Anterior","Deltoides Anterior","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,4,3.2,2.5,0.0],
  ["bb2_bent_row_v","Remo Inclinado V","Remo barra agarre V","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Barra","Tiron","upper","posterior",4,5,3.2,2.5,0.2],
  ["bb2_bent_row_wide","Remo Inclinado Ancho","Remo agarre ancho","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Barra","Tiron","upper","posterior",4,5,3.2,2.5,0.2],
  ["bb2_curl_lying","Curl Tumbado Barra","Curl tumbado banco","Biceps","Biceps","Hipertrofia","Aislamiento","Barra","Tiron","upper","anterior",3,4,1.8,1.5,0.0],
  ["bb2_skull_crusher","Skull Crusher","Ext triceps tumbado","Triceps","Triceps","Hipertrofia","Aislamiento","Barra","Empuje","upper","anterior",3,5,2.0,1.8,0.0],
  ["bb2_clean","Clean","Clean power","Espalda Baja","Espalda Baja","Fuerza","Basico","Barra","Bisagra","full","posterior",4,8,3.5,3.0,0.3],
  ["bb2_power_clean","Power Clean","Power clean","Espalda Baja","Espalda Baja","Fuerza","Basico","Barra","Bisagra","full","posterior",4,8,3.5,3.0,0.3],
  ["bb2_snatch","Snatch","Snatch completo","Espalda Baja","Espalda Baja","Fuerza","Basico","Barra","Bisagra","full","posterior",4,9,3.8,3.2,0.3],
  ["bb2_high_pull","High Pull","Tiron alto barra","Trapecio","Trapecio","Fuerza","Accesorio","Barra","Tiron","upper","anterior",3,5,2.8,2.2,0.2],
  ["bb2_press_ez_incline","Press EZ Inclinado","Press EZ banco inclinado","Triceps","Triceps","Hipertrofia","Aislamiento","Barra","Empuje","upper","anterior",3,5,2.0,1.8,0.0],
  ["bb2_landmine_row","Remo Landmine","Remo landmine","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Barra","Tiron","upper","posterior",3,4,2.8,2.2,0.0],
  ["bb2_landmine_press","Press Landmine","Press landmine vertical","Pectoral Medio","Pectoral Medio","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,4,2.8,2.2,0.0],
  ["bb2_landmine_squat","Squat Landmine","Squat landmine","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Barra","Sentadilla","lower","anterior",3,4,3.0,2.5,0.2],
  ["bb2_meadows_row_v","Remo Meadows V","Meadows variante","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Barra","Tiron","upper","posterior",4,6,3.2,2.5,0.2],
  ["bb2_yates_row","Remo Yates","Remo Yates inclinado","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Barra","Tiron","upper","posterior",4,5,3.2,2.5,0.2],
  ["bb2_pendlay_row","Remo Pendlay","Remo Pendlay","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Barra","Tiron","upper","posterior",4,5,3.2,2.5,0.0],
  ["bb2_sumo_deadlift","Peso Muerto Sumo","Deadlift sumo","Espalda Baja","Espalda Baja","Fuerza","Basico","Barra","Bisagra","lower","posterior",4,6,3.8,3.2,0.2],
  ["bb2_conventional_dl","Peso Muerto Convencional","Deadlift convencional","Espalda Baja","Espalda Baja","Fuerza","Basico","Barra","Bisagra","lower","posterior",4,6,3.8,3.2,0.2],
  ["bb2_front_squat_pause","Front Squat Pausa","Front squat pausa","Cuadriceps","Cuadriceps","Fuerza","Basico","Barra","Sentadilla","lower","anterior",4,6,3.5,3.0,0.5],
  ["bb2_back_squat_pause","Back Squat Pausa","Back squat pausa","Cuadriceps","Cuadriceps","Fuerza","Basico","Barra","Sentadilla","lower","anterior",4,5,3.5,2.8,0.5],
  ["bb2_cg_bench","Press Banca CG","Banca close grip","Triceps","Triceps","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,5,3.0,2.8,0.0],
  ["bb2_lying_tricep","Ext Triceps Tumbado","Extension triceps barra","Triceps","Triceps","Hipertrofia","Aislamiento","Barra","Empuje","upper","anterior",3,5,2.0,1.8,0.0],
  ["bb2_curl_preacher","Curl Predicador Barra","Curl predicador barra","Biceps","Biceps","Hipertrofia","Aislamiento","Barra","Tiron","upper","anterior",3,3,1.8,1.5,0.0],
  ["bb2_incline_curl","Curl Inclinado Barra","Curl banco inclinado","Biceps","Biceps","Hipertrofia","Aislamiento","Barra","Tiron","upper","anterior",3,4,1.8,1.5,0.0],
  ["bb2_21_curl","Curl 21","Curl 21 repeticiones","Biceps","Biceps","Hipertrofia","Aislamiento","Barra","Tiron","upper","anterior",2,4,1.8,1.5,0.0],
  ["bb2_squat_slow","Sentadilla Lenta","Squat tempo lento","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Barra","Sentadilla","lower","anterior",4,5,3.5,2.8,0.3],
  ["bb2_rdl_slow","RDL Lento","RDL tempo lento","Isquiosurales","Isquiosurales","Hipertrofia","Basico","Barra","Bisagra","lower","posterior",3,5,3.0,2.5,0.3],
  ["bb2_good_morning_seated","Good Morning Sentado","Good morning sentado","Isquiosurales","Isquiosurales","Hipertrofia","Accesorio","Barra","Bisagra","lower","posterior",3,5,2.5,2.0,0.0],
  ["bb2_pullover_ez","Pullover EZ","Pullover barra EZ","Pectoral Medio","Pectoral Medio","Hipertrofia","Aislamiento","Barra","Tiron","upper","anterior",3,4,1.8,1.5,0.0],
  ["bb2_jefferson_deadlift","Jefferson Deadlift","Deadlift Jefferson","Espalda Baja","Espalda Baja","Fuerza","Basico","Barra","Bisagra","lower","posterior",4,6,3.5,2.8,0.2],
  ["bb2_suitcase_deadlift","Peso Muerto Maletin","Deadlift unilateral","Espalda Baja","Espalda Baja","Resistencia","Accesorio","Barra","Bisagra","lower","posterior",3,5,2.8,2.2,0.0],
  ["bb2_snatch_grip_high_pull","Snatch High Pull","High pull agarre snatch","Trapecio","Trapecio","Fuerza","Accesorio","Barra","Tiron","upper","anterior",4,7,3.0,2.5,0.2],
  ["bb2_romanian_deadlift","RDL Barra","RDL con barra","Isquiosurales","Isquiosurales","Hipertrofia","Basico","Barra","Bisagra","lower","posterior",3,5,3.2,2.5,0.3],
  ["bb2_push_press","Push Press","Push press","Deltoides Anterior","Deltoides Anterior","Fuerza","Basico","Barra","Empuje","upper","anterior",3,5,3.2,2.8,0.2],
  ["bb2_jerk","Jerk","Jerk desde rack","Deltoides Anterior","Deltoides Anterior","Fuerza","Basico","Barra","Empuje","upper","anterior",4,8,3.5,3.0,0.3],
  ["bb2_bench_slow","Press Banca Lento","Banca tempo lento","Pectoral Medio","Pectoral Medio","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,4,3.0,2.5,0.0],
  ["bb2_decline_skull","Skull Crusher Declive","Skull crusher declive","Triceps","Triceps","Hipertrofia","Aislamiento","Barra","Empuje","upper","anterior",4,5,2.0,1.8,0.0],
  ["bb2_seated_ohp","Press Sentado","Press militar sentado","Deltoides Anterior","Deltoides Anterior","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,4,3.2,2.5,0.0],
  ["bb2_bradford_press","Bradford Press","Bradford press","Deltoides Anterior","Deltoides Anterior","Hipertrofia","Accesorio","Barra","Empuje","upper","anterior",3,5,2.8,2.2,0.0],
  ["bb2_wide_grip_bench","Press Banca Ancho","Banca agarre muy ancho","Pectoral Medio","Pectoral Medio","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,4,3.0,2.5,0.0],
];
BB2.forEach(e=>EX.push(["db_exp3_"+e[0],e[1],e[2],e[3],e[4],e[5],e[6],e[7],e[8],e[9],e[10],e[11],e[12],e[13],e[14],e[15]]));

// Mas maquinas y poleas - 90
const MQ2 = [
  ["mq2_chest_press_vertical","Press Pecho Vertical","Maquina press vertical","Pectoral Medio","Pectoral Medio","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,3.0,2.2,0.0],
  ["mq2_cable_crossover_high","Cruce Polea Alta","Cruces polea alta","Pectoral Medio","Pectoral Medio","Hipertrofia","Aislamiento","Polea","Empuje","upper","anterior",2,3,1.8,1.5,0.0],
  ["mq2_cable_crossover_mid","Cruce Polea Media","Cruces polea media","Pectoral Medio","Pectoral Medio","Hipertrofia","Aislamiento","Polea","Empuje","upper","anterior",2,3,1.8,1.5,0.0],
  ["mq2_cable_crossover_low","Cruce Polea Baja","Cruces polea baja","Pectoral Inferior","Pectoral Inferior","Hipertrofia","Aislamiento","Polea","Empuje","upper","anterior",2,3,1.8,1.5,0.0],
  ["mq2_cable_fly_incline","Cruce Inclinado Polea","Cruces inclinados polea","Pectoral Superior","Pectoral Superior","Hipertrofia","Aislamiento","Polea","Empuje","upper","anterior",2,4,1.8,1.5,0.0],
  ["mq2_lat_pulldown_behind","Jalon Atras Nuca","Jalon por detras","Dorsal Ancho","Dorsales","Hipertrofia","Basico","Polea","Tiron","upper","posterior",2,5,3.0,2.5,0.2],
  ["mq2_straight_arm_rope","Jalon Brazos Rectos Cuerda","Dorsal cuerda","Dorsal Ancho","Dorsales","Hipertrofia","Aislamiento","Polea","Tiron","upper","posterior",2,3,2.2,1.8,0.0],
  ["mq2_seated_row_close","Remo Sentado Cerrado","Remo polea cerrado","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Polea","Tiron","upper","posterior",2,3,3.0,2.5,0.2],
  ["mq2_seated_row_wide","Remo Sentado Ancho","Remo polea ancho","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Polea","Tiron","upper","posterior",2,3,3.0,2.5,0.2],
  ["mq2_face_pull_dual","Face Pull Doble","Face pull doble polea","Deltoides Posterior","Deltoides Posterior","Hipertrofia","Aislamiento","Polea","Tiron","upper","posterior",2,3,1.8,1.5,0.0],
  ["mq2_cable_lateral_low","Lateral Polea Baja","Lateral polea baja","Deltoides Lateral","Deltoides Lateral","Hipertrofia","Aislamiento","Polea","Empuje","upper","anterior",2,3,1.6,1.2,0.0],
  ["mq2_cable_rear_delt","Deltoides Posterior Polea","Laterales inclinado polea","Deltoides Posterior","Deltoides Posterior","Hipertrofia","Aislamiento","Polea","Tiron","upper","posterior",2,3,1.6,1.2,0.0],
  ["mq2_cable_curl_single","Curl Polea Unilateral","Curl polea un brazo","Biceps","Biceps","Hipertrofia","Aislamiento","Polea","Tiron","upper","anterior",1,2,1.8,1.5,0.0],
  ["mq2_cable_curl_high","Curl Polea Alta","Curl polea alta","Biceps","Biceps","Hipertrofia","Aislamiento","Polea","Tiron","upper","anterior",2,3,1.8,1.5,0.0],
  ["mq2_tricep_ext_single","Ext Triceps Polea Unilateral","Extension triceps un brazo","Triceps","Triceps","Hipertrofia","Aislamiento","Polea","Empuje","upper","anterior",1,2,1.6,1.2,0.0],
  ["mq2_tricep_ext_high","Ext Triceps Polea Alta","Extension triceps polea alta","Triceps","Triceps","Hipertrofia","Aislamiento","Polea","Empuje","upper","anterior",2,3,1.8,1.5,0.0],
  ["mq2_pulldown_single","Jalon Unilateral","Jalon un brazo","Dorsal Ancho","Dorsales","Hipertrofia","Basico","Polea","Tiron","upper","posterior",2,3,2.8,2.2,0.0],
  ["mq2_row_single_low","Remo Polea Baja Unilateral","Remo bajo un brazo","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Polea","Tiron","upper","posterior",2,3,2.8,2.2,0.0],
  ["mq2_shrug_cable","Encogimiento Polea","Encogimiento polea","Trapecio","Trapecio","Hipertrofia","Aislamiento","Polea","Tiron","upper","posterior",2,2,2.0,1.5,0.0],
  ["mq2_pec_deck_reverse","Pec Deck Inverso","Pec deck inverso deltoides","Deltoides Posterior","Deltoides Posterior","Hipertrofia","Aislamiento","Maquina","Tiron","upper","posterior",1,2,1.6,1.2,0.0],
  ["mq2_chest_press_iso_low","Press Pecho Isolateral Bajo","Press unilateral bajo","Pectoral Inferior","Pectoral Inferior","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,3.0,2.2,0.0],
  ["mq2_chest_press_iso_high","Press Pecho Isolateral Alto","Press unilateral alto","Pectoral Superior","Pectoral Superior","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,3.0,2.2,0.0],
  ["mq2_cable_pullover","Pullover Polea","Pullover en polea","Dorsal Ancho","Dorsales","Hipertrofia","Aislamiento","Polea","Tiron","upper","posterior",2,3,2.2,1.8,0.0],
  ["mq2_incline_chest_machine","Press Inclinado Maquina","Maquina inclinada","Pectoral Superior","Pectoral Superior","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,2,3.0,2.2,0.0],
  ["mq2_decline_chest_machine","Press Declinado Maquina","Maquina declinada","Pectoral Inferior","Pectoral Inferior","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,2,3.0,2.2,0.0],
  ["mq2_assisted_pull_up","Dominada Asistida","Dominada con asistencia","Dorsal Ancho","Dorsales","Resistencia","Basico","Maquina","Tiron","upper","posterior",2,3,2.8,2.2,0.2],
  ["mq2_assisted_dip","Fondos Asistidos","Fondos con asistencia","Triceps","Triceps","Resistencia","Basico","Maquina","Empuje","upper","anterior",2,3,2.5,2.0,0.0],
  ["mq2_cable_chest_press","Press Pecho Polea","Press pecho polea","Pectoral Medio","Pectoral Medio","Hipertrofia","Basico","Polea","Empuje","upper","anterior",2,3,3.0,2.2,0.0],
  ["mq2_cable_row_straight","Remo Polea Barra","Remo polea barra recta","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Polea","Tiron","upper","posterior",2,3,3.0,2.5,0.2],
  ["mq2_upright_row_cable","Remo Menton Polea","Remo vertical polea","Deltoides Lateral","Deltoides Lateral","Hipertrofia","Accesorio","Polea","Tiron","upper","anterior",2,3,2.2,1.8,0.0],
  ["mq2_cable_curl_preacher","Curl Predicador Polea","Curl predicador polea","Biceps","Biceps","Hipertrofia","Aislamiento","Polea","Tiron","upper","anterior",2,3,1.8,1.5,0.0],
  ["mq2_cable_overhead_ext","Ext Triceps Overhead Polea","Extension overhead polea","Triceps","Triceps","Hipertrofia","Aislamiento","Polea","Empuje","upper","anterior",2,3,1.8,1.5,0.0],
  ["mq2_lying_cable_curl","Curl Tumbado Polea","Curl tumbado polea","Biceps","Biceps","Hipertrofia","Aislamiento","Polea","Tiron","upper","anterior",2,4,1.8,1.5,0.0],
  ["mq2_woodchop_rotating","Wood Chop Rotacion","Wood chop rotacion","Oblicuos","Abdomen","Hipertrofia","Accesorio","Polea","Rotacion","full","full",2,4,2.0,1.5,0.0],
  ["mq2_cable_crunch_kneel","Crunch Polea Rodillas","Crunch polea arrodillado","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Polea","Flexion","full","anterior",2,3,2.0,1.5,0.0],
  ["mq2_rope_crunch","Crunch Cuerda","Crunch con cuerda","Recto Abdominal","Abdomen","Hipertrofia","Aislamiento","Polea","Flexion","full","anterior",2,2,1.8,1.5,0.0],
  ["mq2_leg_curl_standing","Curl Femoral Pie","Curl isquios de pie","Isquiosurales","Isquiosurales","Hipertrofia","Aislamiento","Maquina","Flexion","lower","posterior",2,3,2.0,1.5,0.0],
  ["mq2_leg_extension_45","Extension Cuadriceps 45","Extension 45 grados","Cuadriceps","Cuadriceps","Hipertrofia","Aislamiento","Maquina","Extension","lower","anterior",2,2,2.0,1.5,0.0],
  ["mq2_calf_raise_leg_press","Gemelos Prensadora","Gemelos prensa piernas","Gastrocnemio","Pantorrillas","Hipertrofia","Aislamiento","Maquina","Extension","lower","posterior",2,2,2.0,1.5,0.3],
  ["mq2_hack_squat_narrow","Hack Squat Cerrado","Hack squat piernas juntas","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Maquina","Sentadilla","lower","anterior",3,4,3.5,2.8,0.5],
  ["mq2_hack_squat_wide","Hack Squat Ancho","Hack squat piernas anchas","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Maquina","Sentadilla","lower","anterior",3,4,3.5,2.8,0.5],
  ["mq2_v_squat_narrow","V-Squat Cerrado","V-squat cerrado","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Maquina","Sentadilla","lower","anterior",3,4,3.5,2.8,0.5],
  ["mq2_glute_ham_raise","GHR Maquina","Glute ham raise","Isquiosurales","Isquiosurales","Hipertrofia","Aislamiento","Maquina","Flexion","lower","posterior",3,6,2.8,2.2,0.0],
  ["mq2_hip_thrust_machine","Hip Thrust Maquina","Hip thrust maquina","Gluteos","Gluteos","Hipertrofia","Basico","Maquina","Bisagra","lower","posterior",2,3,3.0,2.5,0.0],
  ["mq2_back_extension","Extension Espalda Maquina","Extension espalda maquina","Espalda Baja","Espalda Baja","Hipertrofia","Aislamiento","Maquina","Extension","full","posterior",2,2,2.0,1.5,0.0],
  ["mq2_seated_leg_curl","Curl Femoral Sentado Maq","Curl sentado maquina","Isquiosurales","Isquiosurales","Hipertrofia","Aislamiento","Maquina","Flexion","lower","posterior",2,2,2.0,1.5,0.0],
  ["mq2_cable_pull_through","Pull Through","Pull through polea","Gluteos","Gluteos","Hipertrofia","Accesorio","Polea","Bisagra","lower","posterior",2,4,2.8,2.2,0.0],
  ["mq2_cable_rdl","RDL Polea","RDL en polea","Isquiosurales","Isquiosurales","Hipertrofia","Accesorio","Polea","Bisagra","lower","posterior",2,4,2.8,2.2,0.2],
  ["mq2_cable_leg_curl","Curl Femoral Polea","Curl isquios polea","Isquiosurales","Isquiosurales","Hipertrofia","Aislamiento","Polea","Flexion","lower","posterior",2,3,2.0,1.5,0.0],
  ["mq2_cable_leg_extension","Extension Polea","Extension cuadriceps polea","Cuadriceps","Cuadriceps","Hipertrofia","Aislamiento","Polea","Extension","lower","anterior",2,3,2.0,1.5,0.0],
  ["mq2_cable_hip_abduction","Abduccion Polea","Abduccion cadera polea","Gluteo Medio","Gluteos","Hipertrofia","Aislamiento","Polea","Otro","lower","posterior",2,3,1.6,1.2,0.0],
  ["mq2_cable_hip_adduction","Aduccion Polea","Aduccion cadera polea","Aductores","Aductores","Hipertrofia","Aislamiento","Polea","Otro","lower","posterior",2,3,1.6,1.2,0.0],
  ["mq2_cable_glute_kickback","Patada Gluteo Polea","Patada gluteo polea","Gluteos","Gluteos","Hipertrofia","Aislamiento","Polea","Bisagra","lower","posterior",2,3,2.0,1.5,0.0],
  ["mq2_smith_rdl","RDL Smith","RDL en Smith","Isquiosurales","Isquiosurales","Hipertrofia","Basico","Maquina","Bisagra","lower","posterior",3,4,3.0,2.5,0.2],
  ["mq2_smith_front_squat","Front Squat Smith","Front squat Smith","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Maquina","Sentadilla","lower","anterior",3,4,3.5,2.8,0.5],
  ["mq2_smith_hip_thrust","Hip Thrust Smith","Hip thrust Smith","Gluteos","Gluteos","Hipertrofia","Basico","Maquina","Bisagra","lower","posterior",3,4,3.0,2.5,0.0],
  ["mq2_cable_wrist_curl","Curl Muneca Polea","Flexion muneca polea","Antebrazo","Antebrazo","Hipertrofia","Aislamiento","Polea","Flexion","upper","anterior",1,2,1.2,1.0,0.0],
  ["mq2_cable_reverse_curl","Curl Inverso Polea","Curl inverso polea","Antebrazo","Antebrazo","Hipertrofia","Aislamiento","Polea","Tiron","upper","anterior",1,2,1.6,1.2,0.0],
  ["mq2_seated_calf_raise","Gemelos Sentado Maquina","Gemelos sentado maquina","Soleo","Pantorrillas","Hipertrofia","Aislamiento","Maquina","Extension","lower","posterior",2,2,2.0,1.5,0.3],
  ["mq2_standing_calf_raise","Gemelos Pie Maquina","Gemelos maquina pie","Gastrocnemio","Pantorrillas","Hipertrofia","Aislamiento","Maquina","Extension","lower","posterior",2,2,2.0,1.5,0.5],
  ["mq2_donkey_calf_raise","Gemelos Burro Maquina","Gemelos maquina burro","Gastrocnemio","Pantorrillas","Hipertrofia","Aislamiento","Maquina","Extension","lower","posterior",2,3,2.0,1.5,0.3],
  ["mq2_unilateral_pulldown","Jalon Unilateral Polea","Jalon un brazo polea","Dorsal Ancho","Dorsales","Hipertrofia","Basico","Polea","Tiron","upper","posterior",2,3,2.8,2.2,0.0],
  ["mq2_unilateral_row","Remo Unilateral Polea","Remo un brazo polea","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Polea","Tiron","upper","posterior",2,3,2.8,2.2,0.0],
  ["mq2_incline_bench_machine","Press Inclinado Smith","Inclinado Smith","Pectoral Superior","Pectoral Superior","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,3.0,2.5,0.0],
  ["mq2_decline_bench_machine","Press Declinado Smith","Declinado Smith","Pectoral Inferior","Pectoral Inferior","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,3.0,2.5,0.0],
  ["mq2_pec_fly_machine","Pec Deck Maquina","Pec deck clasico","Pectoral Medio","Pectoral Medio","Hipertrofia","Aislamiento","Maquina","Empuje","upper","anterior",1,2,1.6,1.2,0.0],
  ["mq2_chest_press_converging","Press Convergente","Maquina convergente","Pectoral Medio","Pectoral Medio","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,3.0,2.2,0.0],
  ["mq2_shoulder_press_machine","Press Hombro Maquina","Maquina press hombro","Deltoides Anterior","Deltoides Anterior","Hipertrofia","Basico","Maquina","Empuje","upper","anterior",2,3,2.8,2.2,0.0],
  ["mq2_lateral_raise_machine","Lateral Maquina","Maquina lateral","Deltoides Lateral","Deltoides Lateral","Hipertrofia","Aislamiento","Maquina","Empuje","upper","anterior",1,2,1.6,1.2,0.0],
  ["mq2_rear_delt_machine","Deltoides Posterior Maquina","Maquina deltoides posterior","Deltoides Posterior","Deltoides Posterior","Hipertrofia","Aislamiento","Maquina","Tiron","upper","posterior",1,2,1.6,1.2,0.0],
  ["mq2_bicep_curl_machine","Curl Biceps Maquina","Maquina curl biceps","Biceps","Biceps","Hipertrofia","Aislamiento","Maquina","Tiron","upper","anterior",1,2,1.8,1.5,0.0],
  ["mq2_preacher_curl_machine","Curl Predicador Maquina","Maquina predicador","Biceps","Biceps","Hipertrofia","Aislamiento","Maquina","Tiron","upper","anterior",1,2,1.8,1.5,0.0],
  ["mq2_tricep_dip_machine","Fondos Maquina","Maquina fondos","Triceps","Triceps","Resistencia","Basico","Maquina","Empuje","upper","anterior",2,3,2.5,2.0,0.0],
  ["mq2_tricep_ext_machine","Ext Triceps Maquina","Maquina extension triceps","Triceps","Triceps","Hipertrofia","Aislamiento","Maquina","Empuje","upper","anterior",1,2,1.6,1.2,0.0],
  ["mq2_cable_fly_decline","Cruce Declive Polea","Cruces declive polea","Pectoral Inferior","Pectoral Inferior","Hipertrofia","Aislamiento","Polea","Empuje","upper","anterior",2,4,1.8,1.5,0.0],
  ["mq2_cable_row_parallel","Remo Polea Paralelo","Remo asas paralelas","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Polea","Tiron","upper","posterior",2,3,3.0,2.5,0.2],
  ["mq2_low_pulley_row","Remo Polea Baja","Remo polea baja","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Polea","Tiron","upper","posterior",2,3,3.0,2.5,0.2],
  ["mq2_high_pulley_row","Remo Polea Alta","Remo polea alta","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Polea","Tiron","upper","posterior",2,3,2.8,2.2,0.2],
  ["mq2_cable_shrug","Encogimiento Polea","Encogimiento polea","Trapecio","Trapecio","Hipertrofia","Aislamiento","Polea","Tiron","upper","posterior",2,2,2.0,1.5,0.0],
  ["mq2_landmine_press_ang","Press Landmine Angulo","Press landmine angulado","Pectoral Medio","Pectoral Medio","Hipertrofia","Basico","Barra","Empuje","upper","anterior",3,4,2.8,2.2,0.0],
  ["mq2_landmine_row_ang","Remo Landmine Angulo","Remo landmine angulado","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Barra","Tiron","upper","posterior",3,4,2.8,2.2,0.0],
  ["mq2_t_bar_row_handle","Remo T-Bar Asas","Remo T-bar con asas","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Barra","Tiron","upper","posterior",3,5,3.2,2.5,0.2],
  ["mq2_chest_supported_tbar","Remo T-Bar Apoyado","Remo T-bar con apoyo","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Barra","Tiron","upper","posterior",4,4,3.2,2.5,0.0],
  ["mq2_single_arm_pulldown","Jalon Un Brazo","Jalon unilateral","Dorsal Ancho","Dorsales","Hipertrofia","Basico","Polea","Tiron","upper","posterior",2,3,2.8,2.2,0.0],
  ["mq2_cable_curl_concentration","Curl Concentracion Polea","Curl concentracion polea","Biceps","Biceps","Hipertrofia","Aislamiento","Polea","Tiron","upper","anterior",2,3,1.8,1.5,0.0],
  ["mq2_reverse_pushdown","Pushdown Inverso","Pushdown agarre inverso","Triceps","Triceps","Hipertrofia","Aislamiento","Polea","Empuje","upper","anterior",1,3,1.8,1.5,0.0],
  ["mq2_close_grip_pulldown","Jalon Cerrado","Jalon agarre cerrado","Dorsal Ancho","Dorsales","Hipertrofia","Basico","Polea","Tiron","upper","posterior",2,3,3.0,2.5,0.2],
  ["mq2_wide_grip_pulldown","Jalon Ancho","Jalon agarre ancho","Dorsal Ancho","Dorsales","Hipertrofia","Basico","Polea","Tiron","upper","posterior",2,3,3.0,2.5,0.2],
  ["mq2_neutral_grip_pulldown","Jalon Neutro","Jalon agarre neutro","Dorsal Ancho","Dorsales","Hipertrofia","Basico","Polea","Tiron","upper","posterior",2,3,3.0,2.5,0.2],
  ["mq2_preacher_ez_bar","Curl Predicador EZ","Curl predicador EZ","Biceps","Biceps","Hipertrofia","Aislamiento","Barra","Tiron","upper","anterior",3,3,1.8,1.5,0.0],
  ["mq2_incline_db_fly","Pechos Inclinado Mancuerna","Aperturas inclinadas DB","Pectoral Superior","Pectoral Superior","Hipertrofia","Aislamiento","Mancuerna","Empuje","upper","anterior",3,4,1.6,1.2,0.0],
  ["mq2_flat_db_fly","Pechos Plano Mancuerna","Aperturas plano DB","Pectoral Medio","Pectoral Medio","Hipertrofia","Aislamiento","Mancuerna","Empuje","upper","anterior",3,3,1.6,1.2,0.0],
  ["mq2_decline_db_fly","Pechos Declinado Mancuerna","Aperturas declinadas DB","Pectoral Inferior","Pectoral Inferior","Hipertrofia","Aislamiento","Mancuerna","Empuje","upper","anterior",3,4,1.6,1.2,0.0],
  ["mq2_db_pullover","Pullover Mancuerna","Pullover mancuerna","Pectoral Medio","Pectoral Medio","Hipertrofia","Aislamiento","Mancuerna","Tiron","upper","anterior",3,4,1.8,1.5,0.0],
  ["mq2_db_incline_press","Press Inclinado Mancuerna","Press inclinado DB","Pectoral Superior","Pectoral Superior","Hipertrofia","Basico","Mancuerna","Empuje","upper","anterior",3,4,3.0,2.5,0.0],
  ["mq2_db_flat_press","Press Plano Mancuerna","Press plano DB","Pectoral Medio","Pectoral Medio","Hipertrofia","Basico","Mancuerna","Empuje","upper","anterior",3,4,3.0,2.5,0.0],
  ["mq2_db_decline_press","Press Declinado Mancuerna","Press declinado DB","Pectoral Inferior","Pectoral Inferior","Hipertrofia","Basico","Mancuerna","Empuje","upper","anterior",4,4,3.0,2.5,0.0],
  ["mq2_db_shoulder_press","Press Hombro Mancuerna","Press hombro DB","Deltoides Anterior","Deltoides Anterior","Hipertrofia","Basico","Mancuerna","Empuje","upper","anterior",3,4,2.8,2.2,0.0],
  ["mq2_db_arnold_press","Arnold Press","Arnold press mancuerna","Deltoides Anterior","Deltoides Anterior","Hipertrofia","Basico","Mancuerna","Empuje","upper","anterior",3,5,2.8,2.2,0.0],
  ["mq2_db_lateral_raise","Lateral Mancuerna","Elevaciones laterales DB","Deltoides Lateral","Deltoides Lateral","Hipertrofia","Aislamiento","Mancuerna","Empuje","upper","anterior",2,2,1.6,1.2,0.0],
  ["mq2_db_front_raise","Frontal Mancuerna","Elevaciones frontales DB","Deltoides Anterior","Deltoides Anterior","Hipertrofia","Aislamiento","Mancuerna","Empuje","upper","anterior",2,2,1.6,1.2,0.0],
  ["mq2_db_bent_lateral","Lateral Inclinado Mancuerna","Laterales inclinado DB","Deltoides Posterior","Deltoides Posterior","Hipertrofia","Aislamiento","Mancuerna","Tiron","upper","posterior",3,4,1.6,1.2,0.0],
  ["mq2_db_row_one_arm","Remo Unilateral Mancuerna","Remo un brazo DB","Dorsal Ancho","Dorsales","Hipertrofia","Accesorio","Mancuerna","Tiron","upper","posterior",3,4,2.8,2.2,0.0],
  ["mq2_db_shrug","Encogimiento Mancuerna","Encogimiento DB","Trapecio","Trapecio","Hipertrofia","Aislamiento","Mancuerna","Tiron","upper","posterior",2,2,2.0,1.5,0.0],
  ["mq2_db_curl","Curl Mancuerna","Curl biceps DB","Biceps","Biceps","Hipertrofia","Aislamiento","Mancuerna","Tiron","upper","anterior",2,2,1.8,1.5,0.0],
  ["mq2_db_hammer_curl","Curl Martillo Mancuerna","Curl martillo DB","Biceps","Biceps","Hipertrofia","Aislamiento","Mancuerna","Tiron","upper","anterior",2,2,1.8,1.5,0.0],
  ["mq2_db_tricep_ext","Ext Triceps Mancuerna","Extension triceps DB","Triceps","Triceps","Hipertrofia","Aislamiento","Mancuerna","Empuje","upper","anterior",2,3,1.6,1.2,0.0],
  ["mq2_db_kickback","Kickback Mancuerna","Kickback triceps DB","Triceps","Triceps","Hipertrofia","Aislamiento","Mancuerna","Empuje","upper","anterior",2,3,1.5,1.2,0.0],
  ["mq2_db_goblet_squat","Sentadilla Copa Mancuerna","Goblet squat DB","Cuadriceps","Cuadriceps","Hipertrofia","Basico","Mancuerna","Sentadilla","lower","anterior",2,4,3.0,2.5,0.3],
  ["mq2_db_rdl","RDL Mancuerna","RDL con mancuernas","Isquiosurales","Isquiosurales","Hipertrofia","Basico","Mancuerna","Bisagra","lower","posterior",2,4,2.8,2.2,0.2],
  ["mq2_db_lunge","Zancada Mancuerna","Zancada con DB","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Mancuerna","Sentadilla","lower","anterior",2,4,2.8,2.2,0.2],
  ["mq2_db_step_up","Step Up Mancuerna","Step up con DB","Cuadriceps","Cuadriceps","Hipertrofia","Accesorio","Mancuerna","Sentadilla","lower","anterior",2,3,2.5,2.0,0.2],
  ["mq2_db_hip_thrust","Hip Thrust Mancuerna","Hip thrust DB","Gluteos","Gluteos","Hipertrofia","Basico","Mancuerna","Bisagra","lower","posterior",3,4,2.8,2.2,0.0],
  ["mq2_db_calf_raise","Gemelos Mancuerna","Gemelos con DB","Gastrocnemio","Pantorrillas","Hipertrofia","Aislamiento","Mancuerna","Extension","lower","posterior",1,2,1.8,1.5,0.3],
];
MQ2.forEach(e=>EX.push(["db_exp3_"+e[0],e[1],e[2],e[3],e[4],e[5],e[6],e[7],e[8],e[9],e[10],e[11],e[12],e[13],e[14],e[15]]));
const out = EX.map(e=>L(...e)).join(",\n");
fs.writeFileSync("exp3_bulk.txt", out);
console.log("Generated", EX.length, "exercises");


