const PRETTY_NAMES = {
  "tren_superior_flexiones": "Flexiones de Brazos",
  "triceps_press_frances": "Press Francés",
  "triceps_overhead": "Extensión de Tríceps Overhead",
  "triceps_patada": "Patada de Tríceps",
  "triceps_pushdown": "Pushdown de Tríceps",
  "triceps_rolling_extension": "Rolling Extension de Tríceps",
  "triceps_extension": "Extensión de Tríceps",
  "back_pullover": "Pullover",
  "back_y_raises": "Y-Raises",
  "back_jefferson_curl": "Jefferson Curl",
  "back_extension_lumbar": "Extensión Lumbar",
  "back_buenos_dias": "Buenos Días",
  "deltoides_press_militar_de_pie": "Press Militar de Pie",
  "deltoides_press_hombros_de_pie": "Press de Hombros de Pie",
  "deltoides_press_hombros_sentado": "Press de Hombros Sentado",
  "deltoides_push_press": "Push Press",
  "deltoides_elevaciones_frontales": "Elevaciones Frontales",
  "deltoides_elevaciones_laterales_de_pie": "Elevaciones Laterales de Pie",
  "deltoides_elevaciones_laterales_sentado": "Elevaciones Laterales Sentado",
  "deltoides_elevaciones_laterales": "Elevaciones Laterales",
  "deltoides_y_raises_sentado_banco_inclinado": "Y-Raises Sentado en Banco Inclinado",
  "deltoides_elevaciones_laterales_acostado_banco_plano": "Elevaciones Laterales Acostado en Banco Plano",
  "deltoides_elevaciones_laterales_inclinadas": "Elevaciones Laterales Inclinadas",
  "deltoides_elevaciones_laterales_recostado": "Elevaciones Laterales Recostado",
  "deltoides_lu_raises": "LU-Raises",
  "deltoides_remo_menton": "Remo al Mentón",
  "deltoides_elevaciones_posteriores_de_pie": "Elevaciones Posteriores de Pie",
  "deltoides_elevaciones_posteriores_sentado_banco_plano": "Elevaciones Posteriores Sentado en Banco Plano",
  "deltoides_elevaciones_posteriores_pecho_apoyado": "Elevaciones Posteriores con Pecho Apoyado",
  "deltoides_elevaciones_posteriores_acostado_banco_plano": "Elevaciones Posteriores Acostado en Banco Plano",
  "deltoides_elevaciones_posteriores_arana": "Elevaciones Posteriores Araña",
  "quads_sentadilla_trasera": "Sentadilla Trasera",
  "quads_sentadilla_frontal": "Sentadilla Frontal",
  "quads_sentadilla_bazuca": "Sentadilla Bazuca",
  "quads_sentadilla_somersault": "Sentadilla Somersault",
  "quads_sentadilla_copa": "Sentadilla Copa",
  "quads_sentadilla_hack": "Sentadilla Hack",
  "quads_prensa_piernas": "Prensa de Piernas",
  "quads_extension_cuadriceps": "Extensión de Cuádriceps",
  "quads_sentadilla_bulgara": "Sentadilla Búlgara",
  "quads_zancada_frontal": "Zancada Frontal",
  "quads_zancada_inversa": "Zancada Inversa",
  "quads_zancada_caminando": "Zancada Caminando",
  "quads_step_up_cajon": "Step-Up a Cajón",
  "quads_sentadilla_pistola": "Sentadilla Pistola",
  "quads_sentadilla_cosaca": "Sentadilla Cosaca",
  "quads_sentadilla_sumo": "Sentadilla Sumo",
  "quads_sentadilla_v_squat": "Sentadilla en V-Squat",
  "quads_sentadilla_jefferson": "Sentadilla Jefferson",
  "quads_sentadilla_anderson": "Sentadilla Anderson",
  "quads_sentadilla_cajon": "Sentadilla a Cajón",
  "quads_sentadilla_bulgara_frontal": "Sentadilla Búlgara Frontal",
  "quads_sentadilla_bulgara_zercher": "Sentadilla Búlgara Zercher",
  "quads_sentadilla_bulgara_somersault": "Sentadilla Búlgara Somersault",
  "quads_sentadilla_bulgara_jefferson": "Sentadilla Búlgara Jefferson",
  "quads_step_up_cajon_frontal": "Step-Up a Cajón Frontal",
  "quads_step_up_cajon_zercher": "Step-Up a Cajón Zercher",
  "quads_zancada_frontal_zercher": "Zancada Frontal Zercher",
  "quads_zancada_inversa_frontal": "Zancada Inversa Frontal",
  "quads_zancada_inversa_zercher": "Zancada Inversa Zercher",
  "quads_sentadilla_sumo_frontal": "Sentadilla Sumo Frontal",
  "quads_sentadilla_sumo_zercher": "Sentadilla Sumo Zercher",
  "glutes_patada_gluteo": "Patada de Glúteo",
  "glutes_abduccion_cadera": "Abducción de Cadera",
  "hams_peso_muerto_rumano": "Peso Muerto Rumano",
  "hams_peso_muerto_rumano_b_stance": "Peso Muerto Rumano B-Stance",
  "hams_peso_muerto_piernas_rigidas": "Peso Muerto Piernas Rígidas",
  "hams_buenos_dias": "Buenos Días",
  "hams_peso_muerto_rumano_zercher": "Peso Muerto Rumano Zercher",
  "hams_buenos_dias_zercher": "Buenos Días Zercher",
  "glutes_patada_gluteo_lateral": "Patada de Glúteo Lateral",
  "glutes_step_up_gluteo": "Step-Up de Glúteo",
  "glutes_zancada_cruzada": "Zancada Cruzada",
  "glutes_hiperextension_45": "Hiperextensión 45°",
  "glutes_reverse_hyper": "Reverse Hyper",
  "hams_peso_muerto_convencional": "Peso Muerto Convencional",
  "hams_peso_muerto_sumo": "Peso Muerto Sumo",
  "hams_peso_muerto": "Peso Muerto",
  "hams_pull_through": "Pull-Through",
  "hams_buenos_dias_sentado": "Buenos Días Sentado",
  "hams_peso_muerto_rumano_sumo": "Peso Muerto Rumano Sumo",
  "hams_peso_muerto_convencional_deficit": "Peso Muerto Convencional en Déficit",
  "hams_peso_muerto_rumano_deficit": "Peso Muerto Rumano en Déficit",
  "hams_peso_muerto_sumo_deficit": "Peso Muerto Sumo en Déficit",
  "hams_peso_muerto_piernas_rigidas_deficit": "Peso Muerto Piernas Rígidas en Déficit",
  "hams_peso_muerto_rumano_sumo_deficit": "Peso Muerto Rumano Sumo en Déficit",
  "adductors_aduccion_cadera": "Aducción de Cadera",
  "calves_talones_de_pie": "Elevación de Talones de Pie",
  "calves_talones_donkey": "Elevación de Talones Donkey",
  "calves_talones_sentado": "Elevación de Talones Sentado",
  "calves_tibial_anterior": "Tibial Anterior",
  "forearms_curl_muneca_sentado": "Curl de Muñeca Sentado",
  "forearms_curl_muneca_inverso_sentado": "Curl de Muñeca Inverso Sentado",
  "forearms_paseo_del_granjero": "Paseo del Granjero",
  "neck_flexion_cuello_recostado": "Flexión de Cuello Recostado",
  "neck_extension_cuello_boca_abajo": "Extensión de Cuello Boca Abajo",
  "neck_flexion_lateral_cuello": "Flexión Lateral de Cuello",
  "core_press_pallof": "Press Pallof",
  "core_inclinacion_lateral": "Inclinación Lateral",
  "calves_talones_prensa": "Elevación de Talones en Prensa"
};

function prettifyId(id) {
  if (PRETTY_NAMES[id]) return PRETTY_NAMES[id];
  return id.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}

module.exports = { PRETTY_NAMES, prettifyId };
